-- Generated by scripts/generate.py from palette/palette.json. Do not edit.
-- Nib Light for Lite XL
local style = require "core.style"
local common = require "core.common"

style.background = { common.color "#F2F1EC" }
style.background2 = { common.color "#E7E8E4" }
style.background3 = { common.color "#FAFAF7" }
style.text = { common.color "#182A38" }
style.caret = { common.color "#244D68" }
style.accent = { common.color "#315D78" }
style.dim = { common.color "#59656A" }
style.divider = { common.color "#877F6E" }
style.selection = { common.color "#AFC9C3" }
style.line_number = { common.color "#767970" }
style.line_number2 = { common.color "#1F668E" }
style.line_highlight = { common.color "#E4E7E4" }
style.scrollbar = { common.color "#877F6E" }
style.scrollbar2 = { common.color "#DDE1E0" }

style.syntax["normal"] = { common.color "#182A38" }
style.syntax["symbol"] = { common.color "#684873" }
style.syntax["comment"] = { common.color "#59656A" }
style.syntax["keyword"] = { common.color "#173B59" }
style.syntax["keyword2"] = { common.color "#7C3448" }
style.syntax["number"] = { common.color "#77560F" }
style.syntax["literal"] = { common.color "#536126" }
style.syntax["string"] = { common.color "#17666A" }
style.syntax["operator"] = { common.color "#4F5960" }
style.syntax["function"] = { common.color "#1F668E" }
