-- Generated by scripts/generate.py from palette/palette.json. Do not edit.
-- Nib Dark for Lite XL
local style = require "core.style"
local common = require "core.common"

style.background = { common.color "#181A19" }
style.background2 = { common.color "#20231F" }
style.background3 = { common.color "#272A25" }
style.text = { common.color "#DDDCD2" }
style.caret = { common.color "#C9BE83" }
style.accent = { common.color "#82A6B6" }
style.dim = { common.color "#969C97" }
style.divider = { common.color "#626A64" }
style.selection = { common.color "#3A5550" }
style.line_number = { common.color "#707772" }
style.line_number2 = { common.color "#95B7C8" }
style.line_highlight = { common.color "#222620" }
style.scrollbar = { common.color "#626A64" }
style.scrollbar2 = { common.color "#2D302B" }

style.syntax["normal"] = { common.color "#DDDCD2" }
style.syntax["symbol"] = { common.color "#AF97B7" }
style.syntax["comment"] = { common.color "#969C97" }
style.syntax["keyword"] = { common.color "#7795A7" }
style.syntax["keyword2"] = { common.color "#C17E8B" }
style.syntax["number"] = { common.color "#C5A667" }
style.syntax["literal"] = { common.color "#A3AE72" }
style.syntax["string"] = { common.color "#6FA8A0" }
style.syntax["operator"] = { common.color "#959C98" }
style.syntax["function"] = { common.color "#95B7C8" }
