-- Generated by scripts/generate.py from palette/palette.json. Do not edit.
return {
  background = "#181A19",
  surface = {
    elevated = "#20231F",
    floating = "#272A25",
    subtle = "#2D302B"
  },
  border = {
    default = "#626A64",
    subtle = "#424A44",
    focus = "#779AA8"
  },
  foreground = {
    primary = "#DDDCD2",
    secondary = "#BABCB4",
    muted = "#969C97",
    disabled = "#707772"
  },
  blue_ink = {
    deep = "#7795A7",
    primary = "#83A8BB",
    bright = "#95B7C8"
  },
  moss = {
    primary = "#A3AE72",
    muted = "#899463"
  },
  teal = {
    primary = "#6FA8A0",
    muted = "#648F8B"
  },
  burgundy = "#C17E8B",
  rust = "#C28168",
  violet = "#AF97B7",
  amber = "#C5A667",
  sepia = "#AE967B",
  graphite = "#959C98",
  diagnostic = {
    error = "#CF8389",
    warning = "#C6A565",
    information = "#83A8BB",
    hint = "#6FA8A0",
    success = "#A4B073"
  },
  selection = {
    background = "#3A5550",
    foreground = "#E5E2D8"
  },
  search = {
    background = "#55502F",
    foreground = "#E5E2D8",
    current_background = "#B08E4F",
    current_foreground = "#181A19"
  },
  current_line = "#222620",
  match = {
    background = "#394835",
    foreground = "#DDDCD2"
  },
  focus = "#82A6B6",
  hyperlink = "#8CB2C5",
  diff = {
    add = "#21342A",
    add_text = "#2B553A",
    change = "#273137",
    change_text = "#344752",
    delete = "#3A272D",
    delete_text = "#5C333E",
    foreground = "#CFD1C9"
  },
  cursor = {
    background = "#C9BE83",
    foreground = "#181A19"
  },
  ansi = {
    "#232622",
    "#C1777D",
    "#98A56C",
    "#B89A60",
    "#779BAF",
    "#A88FAF",
    "#669D97",
    "#B9BDB6",
    "#7C8580",
    "#D48A90",
    "#AEBB79",
    "#CDAE6C",
    "#8AAFC2",
    "#BBA0C1",
    "#76AEA7",
    "#DDDCD2"
  },
  style = "dark"
}
