-- Generated by scripts/generate.py from palette/palette.json. Do not edit.
return {
  background = "#0D1822",
  surface = {
    elevated = "#13212C",
    floating = "#182834",
    subtle = "#1E2E39"
  },
  border = {
    default = "#56676F",
    subtle = "#3B4C55",
    focus = "#79A9C8"
  },
  foreground = {
    primary = "#E6E1D3",
    secondary = "#C4C4BA",
    muted = "#9CA7A8",
    disabled = "#748085"
  },
  blue_ink = {
    deep = "#719CBC",
    primary = "#89B6D2",
    bright = "#A1C5DE"
  },
  moss = {
    primary = "#ACBA72",
    muted = "#929F65"
  },
  teal = {
    primary = "#70B6AE",
    muted = "#679A96"
  },
  burgundy = "#D18A96",
  rust = "#D08A6F",
  violet = "#BAA0C4",
  amber = "#D0AE68",
  sepia = "#BBA080",
  graphite = "#9DA9AD",
  diagnostic = {
    error = "#E08B91",
    warning = "#D3B066",
    information = "#89B6D2",
    hint = "#70B6AE",
    success = "#ADBD76"
  },
  selection = {
    background = "#2E5860",
    foreground = "#F0EBDD"
  },
  search = {
    background = "#5C522B",
    foreground = "#F0EBDD",
    current_background = "#C39A45",
    current_foreground = "#0D1822"
  },
  current_line = "#142630",
  match = {
    background = "#364B38",
    foreground = "#E6E1D3"
  },
  focus = "#87B4D0",
  hyperlink = "#8BC1DF",
  diff = {
    add = "#1D332D",
    add_text = "#28513F",
    change = "#1C303D",
    change_text = "#27495B",
    delete = "#3A282D",
    delete_text = "#59323A",
    foreground = "#D7D8CF"
  },
  cursor = {
    background = "#D7C98B",
    foreground = "#0D1822"
  },
  ansi = {
    "#1A2731",
    "#CE737B",
    "#9CAF68",
    "#C4A15D",
    "#78A8CA",
    "#B08FB9",
    "#62AAA5",
    "#C2C5BE",
    "#74838A",
    "#E89095",
    "#B8C97A",
    "#DDBD74",
    "#94C2DE",
    "#C7A8CF",
    "#7AC2BB",
    "#EEE9DC"
  },
  style = "dark"
}
