# Generated by scripts/generate.py from palette/palette.json. Do not edit.
FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:+$FZF_DEFAULT_OPTS }--color=fg:#182A38,fg+:#172A38,bg:#F2F1EC,bg+:#AFC9C3,hl:#1F668E,hl+:#17666A,info:#59656A,border:#877F6E,label:#394B56,prompt:#1F668E,pointer:#7C3448,marker:#526329,spinner:#17666A,header:#705039"
export FZF_DEFAULT_OPTS
