# Generated by scripts/generate.py from palette/palette.json. Do not edit.
FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:+$FZF_DEFAULT_OPTS }--color=fg:#DDDCD2,fg+:#E5E2D8,bg:#181A19,bg+:#3A5550,hl:#95B7C8,hl+:#6FA8A0,info:#969C97,border:#626A64,label:#BABCB4,prompt:#95B7C8,pointer:#C17E8B,marker:#A4B073,spinner:#6FA8A0,header:#AE967B"
export FZF_DEFAULT_OPTS
