" Generated by scripts/generate.py from palette/palette.json. Do not edit.
if exists("syntax_on")
  syntax reset
endif
highlight clear
set background=dark
let g:colors_name = 'nib-dark'

highlight Normal guifg=#DDDCD2 guibg=#181A19 guisp=NONE gui=NONE cterm=NONE
highlight NormalNC guifg=#BABCB4 guibg=#181A19 guisp=NONE gui=NONE cterm=NONE
highlight Cursor guifg=#181A19 guibg=#C9BE83 guisp=NONE gui=NONE cterm=NONE
highlight lCursor guifg=#181A19 guibg=#C9BE83 guisp=NONE gui=NONE cterm=NONE
highlight CursorLine guifg=NONE guibg=#222620 guisp=NONE gui=NONE cterm=NONE
highlight CursorColumn guifg=NONE guibg=#222620 guisp=NONE gui=NONE cterm=NONE
highlight ColorColumn guifg=NONE guibg=#20231F guisp=NONE gui=NONE cterm=NONE
highlight LineNr guifg=#707772 guibg=#181A19 guisp=NONE gui=NONE cterm=NONE
highlight CursorLineNr guifg=#95B7C8 guibg=#222620 guisp=NONE gui=bold cterm=bold
highlight SignColumn guifg=#969C97 guibg=#181A19 guisp=NONE gui=NONE cterm=NONE
highlight FoldColumn guifg=#969C97 guibg=#20231F guisp=NONE gui=NONE cterm=NONE
highlight Folded guifg=#969C97 guibg=#20231F guisp=NONE gui=NONE cterm=NONE
highlight Visual guifg=#E5E2D8 guibg=#3A5550 guisp=NONE gui=NONE cterm=NONE
highlight Search guifg=#E5E2D8 guibg=#55502F guisp=NONE gui=NONE cterm=NONE
highlight IncSearch guifg=#181A19 guibg=#B08E4F guisp=NONE gui=bold cterm=bold
highlight CurSearch guifg=#181A19 guibg=#B08E4F guisp=NONE gui=bold cterm=bold
highlight MatchParen guifg=#DDDCD2 guibg=#394835 guisp=NONE gui=bold cterm=bold
highlight Pmenu guifg=#DDDCD2 guibg=#272A25 guisp=NONE gui=NONE cterm=NONE
highlight PmenuSel guifg=#E5E2D8 guibg=#3A5550 guisp=NONE gui=bold cterm=bold
highlight PmenuSbar guifg=NONE guibg=#2D302B guisp=NONE gui=NONE cterm=NONE
highlight PmenuThumb guifg=NONE guibg=#626A64 guisp=NONE gui=NONE cterm=NONE
highlight StatusLine guifg=#DDDCD2 guibg=#2D302B guisp=NONE gui=bold cterm=bold
highlight StatusLineNC guifg=#969C97 guibg=#20231F guisp=NONE gui=NONE cterm=NONE
highlight TabLine guifg=#969C97 guibg=#20231F guisp=NONE gui=NONE cterm=NONE
highlight TabLineFill guifg=#424A44 guibg=#20231F guisp=NONE gui=NONE cterm=NONE
highlight TabLineSel guifg=#7795A7 guibg=#2D302B guisp=NONE gui=bold cterm=bold
highlight WinSeparator guifg=#626A64 guibg=#181A19 guisp=NONE gui=NONE cterm=NONE
highlight VertSplit guifg=#626A64 guibg=#181A19 guisp=NONE gui=NONE cterm=NONE
highlight WildMenu guifg=#E5E2D8 guibg=#3A5550 guisp=NONE gui=bold cterm=bold
highlight Directory guifg=#83A8BB guibg=NONE guisp=NONE gui=bold cterm=bold
highlight Title guifg=#7795A7 guibg=NONE guisp=NONE gui=bold cterm=bold
highlight Question guifg=#A4B073 guibg=NONE guisp=NONE gui=bold cterm=bold
highlight MoreMsg guifg=#83A8BB guibg=NONE guisp=NONE gui=bold cterm=bold
highlight WarningMsg guifg=#C6A565 guibg=NONE guisp=NONE gui=bold cterm=bold
highlight ErrorMsg guifg=#CF8389 guibg=NONE guisp=NONE gui=bold cterm=bold
highlight NonText guifg=#707772 guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight Whitespace guifg=#707772 guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight SpecialKey guifg=#707772 guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight Conceal guifg=#969C97 guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight Comment guifg=#969C97 guibg=NONE guisp=NONE gui=italic cterm=italic
highlight Constant guifg=#C5A667 guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight String guifg=#6FA8A0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight Character guifg=#C28168 guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight Number guifg=#C5A667 guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight Boolean guifg=#C17E8B guibg=NONE guisp=NONE gui=bold cterm=bold
highlight Float guifg=#C5A667 guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight Identifier guifg=#DDDCD2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight Function guifg=#95B7C8 guibg=NONE guisp=NONE gui=bold cterm=bold
highlight Statement guifg=#7795A7 guibg=NONE guisp=NONE gui=bold cterm=bold
highlight Conditional guifg=#C17E8B guibg=NONE guisp=NONE gui=bold cterm=bold
highlight Repeat guifg=#C17E8B guibg=NONE guisp=NONE gui=bold cterm=bold
highlight Label guifg=#C5A667 guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight Operator guifg=#959C98 guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight Keyword guifg=#7795A7 guibg=NONE guisp=NONE gui=bold cterm=bold
highlight Exception guifg=#C17E8B guibg=NONE guisp=NONE gui=bold cterm=bold
highlight PreProc guifg=#AF97B7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight Include guifg=#83A8BB guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight Define guifg=#AF97B7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight Macro guifg=#AF97B7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight Type guifg=#A3AE72 guibg=NONE guisp=NONE gui=bold cterm=bold
highlight StorageClass guifg=#A3AE72 guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight Structure guifg=#A3AE72 guibg=NONE guisp=NONE gui=bold cterm=bold
highlight Typedef guifg=#A3AE72 guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight Special guifg=#AF97B7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight SpecialChar guifg=#C28168 guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight Tag guifg=#A3AE72 guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight Delimiter guifg=#959C98 guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight SpecialComment guifg=#AE967B guibg=NONE guisp=NONE gui=italic cterm=italic
highlight Debug guifg=#C28168 guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight Underlined guifg=#8CB2C5 guibg=NONE guisp=NONE gui=underline cterm=underline
highlight Ignore guifg=#707772 guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight Error guifg=#CF8389 guibg=NONE guisp=#CF8389 gui=undercurl cterm=undercurl
highlight Todo guifg=#C6A565 guibg=#20231F guisp=NONE gui=bold cterm=bold
highlight SpellBad guifg=NONE guibg=NONE guisp=#CF8389 gui=undercurl cterm=undercurl
highlight SpellCap guifg=NONE guibg=NONE guisp=#83A8BB gui=undercurl cterm=undercurl
highlight SpellRare guifg=NONE guibg=NONE guisp=#6FA8A0 gui=undercurl cterm=undercurl
highlight SpellLocal guifg=NONE guibg=NONE guisp=#C6A565 gui=undercurl cterm=undercurl
highlight DiffAdd guifg=#CFD1C9 guibg=#21342A guisp=NONE gui=NONE cterm=NONE
highlight DiffChange guifg=#CFD1C9 guibg=#273137 guisp=NONE gui=NONE cterm=NONE
highlight DiffDelete guifg=#CFD1C9 guibg=#3A272D guisp=NONE gui=NONE cterm=NONE
highlight DiffText guifg=#CFD1C9 guibg=#344752 guisp=NONE gui=bold cterm=bold

let g:terminal_ansi_colors = ["#232622", "#C1777D", "#98A56C", "#B89A60", "#779BAF", "#A88FAF", "#669D97", "#B9BDB6", "#7C8580", "#D48A90", "#AEBB79", "#CDAE6C", "#8AAFC2", "#BBA0C1", "#76AEA7", "#DDDCD2"]
