" Generated by scripts/generate.py from palette/palette.json. Do not edit.
if exists("syntax_on")
  syntax reset
endif
highlight clear
set background=light
let g:colors_name = 'nib-light'

highlight Normal guifg=#182A38 guibg=#F2F1EC guisp=NONE gui=NONE cterm=NONE
highlight NormalNC guifg=#394B56 guibg=#F2F1EC guisp=NONE gui=NONE cterm=NONE
highlight Cursor guifg=#F2F1EC guibg=#244D68 guisp=NONE gui=NONE cterm=NONE
highlight lCursor guifg=#F2F1EC guibg=#244D68 guisp=NONE gui=NONE cterm=NONE
highlight CursorLine guifg=NONE guibg=#E4E7E4 guisp=NONE gui=NONE cterm=NONE
highlight CursorColumn guifg=NONE guibg=#E4E7E4 guisp=NONE gui=NONE cterm=NONE
highlight ColorColumn guifg=NONE guibg=#E7E8E4 guisp=NONE gui=NONE cterm=NONE
highlight LineNr guifg=#767970 guibg=#F2F1EC guisp=NONE gui=NONE cterm=NONE
highlight CursorLineNr guifg=#1F668E guibg=#E4E7E4 guisp=NONE gui=bold cterm=bold
highlight SignColumn guifg=#59656A guibg=#F2F1EC guisp=NONE gui=NONE cterm=NONE
highlight FoldColumn guifg=#59656A guibg=#E7E8E4 guisp=NONE gui=NONE cterm=NONE
highlight Folded guifg=#59656A guibg=#E7E8E4 guisp=NONE gui=NONE cterm=NONE
highlight Visual guifg=#172A38 guibg=#AFC9C3 guisp=NONE gui=NONE cterm=NONE
highlight Search guifg=#2A2B22 guibg=#DEC06C guisp=NONE gui=NONE cterm=NONE
highlight IncSearch guifg=#182A38 guibg=#BD893E guisp=NONE gui=bold cterm=bold
highlight CurSearch guifg=#182A38 guibg=#BD893E guisp=NONE gui=bold cterm=bold
highlight MatchParen guifg=#24372E guibg=#CAD7B4 guisp=NONE gui=bold cterm=bold
highlight Pmenu guifg=#182A38 guibg=#FAFAF7 guisp=NONE gui=NONE cterm=NONE
highlight PmenuSel guifg=#172A38 guibg=#AFC9C3 guisp=NONE gui=bold cterm=bold
highlight PmenuSbar guifg=NONE guibg=#DDE1E0 guisp=NONE gui=NONE cterm=NONE
highlight PmenuThumb guifg=NONE guibg=#877F6E guisp=NONE gui=NONE cterm=NONE
highlight StatusLine guifg=#182A38 guibg=#DDE1E0 guisp=NONE gui=bold cterm=bold
highlight StatusLineNC guifg=#59656A guibg=#E7E8E4 guisp=NONE gui=NONE cterm=NONE
highlight TabLine guifg=#59656A guibg=#E7E8E4 guisp=NONE gui=NONE cterm=NONE
highlight TabLineFill guifg=#AAA18D guibg=#E7E8E4 guisp=NONE gui=NONE cterm=NONE
highlight TabLineSel guifg=#173B59 guibg=#DDE1E0 guisp=NONE gui=bold cterm=bold
highlight WinSeparator guifg=#877F6E guibg=#F2F1EC guisp=NONE gui=NONE cterm=NONE
highlight VertSplit guifg=#877F6E guibg=#F2F1EC guisp=NONE gui=NONE cterm=NONE
highlight WildMenu guifg=#172A38 guibg=#AFC9C3 guisp=NONE gui=bold cterm=bold
highlight Directory guifg=#285D7C guibg=NONE guisp=NONE gui=bold cterm=bold
highlight Title guifg=#173B59 guibg=NONE guisp=NONE gui=bold cterm=bold
highlight Question guifg=#526329 guibg=NONE guisp=NONE gui=bold cterm=bold
highlight MoreMsg guifg=#285D7C guibg=NONE guisp=NONE gui=bold cterm=bold
highlight WarningMsg guifg=#76540B guibg=NONE guisp=NONE gui=bold cterm=bold
highlight ErrorMsg guifg=#913646 guibg=NONE guisp=NONE gui=bold cterm=bold
highlight NonText guifg=#767970 guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight Whitespace guifg=#767970 guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight SpecialKey guifg=#767970 guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight Conceal guifg=#59656A guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight Comment guifg=#59656A guibg=NONE guisp=NONE gui=italic cterm=italic
highlight Constant guifg=#77560F guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight String guifg=#17666A guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight Character guifg=#8A432C guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight Number guifg=#77560F guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight Boolean guifg=#7C3448 guibg=NONE guisp=NONE gui=bold cterm=bold
highlight Float guifg=#77560F guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight Identifier guifg=#182A38 guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight Function guifg=#1F668E guibg=NONE guisp=NONE gui=bold cterm=bold
highlight Statement guifg=#173B59 guibg=NONE guisp=NONE gui=bold cterm=bold
highlight Conditional guifg=#7C3448 guibg=NONE guisp=NONE gui=bold cterm=bold
highlight Repeat guifg=#7C3448 guibg=NONE guisp=NONE gui=bold cterm=bold
highlight Label guifg=#77560F guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight Operator guifg=#4F5960 guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight Keyword guifg=#173B59 guibg=NONE guisp=NONE gui=bold cterm=bold
highlight Exception guifg=#7C3448 guibg=NONE guisp=NONE gui=bold cterm=bold
highlight PreProc guifg=#684873 guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight Include guifg=#285D7C guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight Define guifg=#684873 guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight Macro guifg=#684873 guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight Type guifg=#536126 guibg=NONE guisp=NONE gui=bold cterm=bold
highlight StorageClass guifg=#536126 guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight Structure guifg=#536126 guibg=NONE guisp=NONE gui=bold cterm=bold
highlight Typedef guifg=#536126 guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight Special guifg=#684873 guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight SpecialChar guifg=#8A432C guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight Tag guifg=#536126 guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight Delimiter guifg=#4F5960 guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight SpecialComment guifg=#705039 guibg=NONE guisp=NONE gui=italic cterm=italic
highlight Debug guifg=#8A432C guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight Underlined guifg=#1C5F8B guibg=NONE guisp=NONE gui=underline cterm=underline
highlight Ignore guifg=#767970 guibg=NONE guisp=NONE gui=NONE cterm=NONE
highlight Error guifg=#913646 guibg=NONE guisp=#913646 gui=undercurl cterm=undercurl
highlight Todo guifg=#76540B guibg=#E7E8E4 guisp=NONE gui=bold cterm=bold
highlight SpellBad guifg=NONE guibg=NONE guisp=#913646 gui=undercurl cterm=undercurl
highlight SpellCap guifg=NONE guibg=NONE guisp=#285D7C gui=undercurl cterm=undercurl
highlight SpellRare guifg=NONE guibg=NONE guisp=#17666A gui=undercurl cterm=undercurl
highlight SpellLocal guifg=NONE guibg=NONE guisp=#76540B gui=undercurl cterm=undercurl
highlight DiffAdd guifg=#263640 guibg=#D8E2C3 guisp=NONE gui=NONE cterm=NONE
highlight DiffChange guifg=#263640 guibg=#D7E1E4 guisp=NONE gui=NONE cterm=NONE
highlight DiffDelete guifg=#263640 guibg=#ECD5D0 guisp=NONE gui=NONE cterm=NONE
highlight DiffText guifg=#263640 guibg=#B8CDD6 guisp=NONE gui=bold cterm=bold

let g:terminal_ansi_colors = ["#1D2B36", "#8D3342", "#526126", "#76540B", "#285D7C", "#70446F", "#17666A", "#4F5960", "#5C686E", "#A22F42", "#62721F", "#8A5B00", "#176594", "#82487B", "#006E74", "#303F49"]
