" Generated by scripts/generate.py from palette/palette.json. Do not edit.
if &background ==# 'light'
  runtime colors/nib-light.vim
else
  runtime colors/nib-dark.vim
endif
let g:colors_name = 'nib'
