#!/usr/bin/env python3
"""Generate all palette-derived Nib assets."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

from theme_utils import CVD_MATRICES, ansi_colors, contrast, get_path, iter_colors, load_palette, oklab_distance

ROOT = Path(__file__).resolve().parents[1]
MARKER = "Generated by scripts/generate.py from palette/palette.json. Do not edit."


def lua_value(value: Any, depth: int = 0) -> str:
    indent = "  " * depth
    child_indent = "  " * (depth + 1)
    if isinstance(value, str):
        return json.dumps(value)
    if isinstance(value, int):
        return str(value)
    if isinstance(value, list):
        if value and isinstance(value[0], dict) and "hex" in value[0]:
            value = [entry["hex"] for entry in value]
        body = ",\n".join(f"{child_indent}{lua_value(child, depth + 1)}" for child in value)
        return "{\n" + body + f"\n{indent}}}"
    if isinstance(value, dict):
        body = ",\n".join(
            f"{child_indent}{key} = {lua_value(child, depth + 1)}" for key, child in value.items()
        )
        return "{\n" + body + f"\n{indent}}}"
    raise TypeError(f"cannot serialize {type(value).__name__} to Lua")


def generated_lua_palette(style: str, mode: dict[str, Any]) -> str:
    runtime_mode = dict(mode)
    runtime_mode["style"] = style
    return f"-- {MARKER}\nreturn {lua_value(runtime_mode)}\n"


def generated_entry(style: str) -> str:
    return (
        f"-- {MARKER}\n"
        f"require(\"nib\").load(\"{style}\", \"nib{'' if style == 'auto' else '-' + style}\")\n"
    )


def generated_ghostty(style: str, mode: dict[str, Any]) -> str:
    title = f"nib-{style}"
    lines = [
        f"# {MARKER}",
        f"# {title} — opaque core theme",
        f"background = {mode['background']}",
        f"foreground = {mode['foreground']['primary']}",
        f"cursor-color = {mode['cursor']['background']}",
        f"cursor-text = {mode['cursor']['foreground']}",
        f"selection-background = {mode['selection']['background']}",
        f"selection-foreground = {mode['selection']['foreground']}",
    ]
    lines.extend(f"palette = {entry['index']}={entry['hex']}" for entry in mode["ansi"])
    return "\n".join(lines) + "\n"


def generated_emacs_theme(style: str, mode: dict[str, Any]) -> str:
    theme = f"nib-{style}"

    def face(name: str, **attributes: str | bool | int) -> str:
        values: list[str] = []
        for key, value in attributes.items():
            attribute = key.replace("_", "-")
            if isinstance(value, bool):
                encoded = "t" if value else "nil"
            elif isinstance(value, int):
                encoded = str(value)
            elif key in {"slant", "weight"}:
                encoded = value
            else:
                encoded = json.dumps(value)
            values.append(f":{attribute} {encoded}")
        return f" '({name} ((t ({' '.join(values)}))))"

    faces = [
        face("default", foreground=mode["foreground"]["primary"], background=mode["background"]),
        face("cursor", foreground=mode["cursor"]["foreground"], background=mode["cursor"]["background"]),
        face("fringe", foreground=mode["foreground"]["muted"], background=mode["background"]),
        face("region", foreground=mode["selection"]["foreground"], background=mode["selection"]["background"], extend=True),
        face("secondary-selection", foreground=mode["match"]["foreground"], background=mode["match"]["background"]),
        face("highlight", foreground=mode["match"]["foreground"], background=mode["match"]["background"]),
        face("hl-line", background=mode["current_line"], extend=True),
        face("line-number", foreground=mode["foreground"]["disabled"], background=mode["background"]),
        face("line-number-current-line", foreground=mode["blue_ink"]["bright"], background=mode["current_line"], weight="bold"),
        face("mode-line", foreground=mode["foreground"]["primary"], background=mode["surface"]["subtle"], box=mode["border"]["default"]),
        face("mode-line-active", foreground=mode["foreground"]["primary"], background=mode["surface"]["subtle"], box=mode["border"]["default"]),
        face("mode-line-inactive", foreground=mode["foreground"]["muted"], background=mode["surface"]["elevated"], box=mode["border"]["subtle"]),
        face("header-line", foreground=mode["foreground"]["secondary"], background=mode["surface"]["elevated"], box=mode["border"]["subtle"]),
        face("vertical-border", foreground=mode["border"]["default"], background=mode["background"]),
        face("window-divider", foreground=mode["border"]["default"], background=mode["background"]),
        face("window-divider-first-pixel", foreground=mode["border"]["default"], background=mode["background"]),
        face("window-divider-last-pixel", foreground=mode["border"]["subtle"], background=mode["background"]),
        face("minibuffer-prompt", foreground=mode["blue_ink"]["bright"], weight="bold"),
        face("link", foreground=mode["hyperlink"], underline=True),
        face("link-visited", foreground=mode["violet"], underline=True),
        face("shadow", foreground=mode["foreground"]["muted"]),
        face("success", foreground=mode["diagnostic"]["success"], weight="bold"),
        face("warning", foreground=mode["diagnostic"]["warning"], weight="bold"),
        face("error", foreground=mode["diagnostic"]["error"], weight="bold"),
        face("match", foreground=mode["match"]["foreground"], background=mode["match"]["background"], weight="bold"),
        face("lazy-highlight", foreground=mode["search"]["foreground"], background=mode["search"]["background"]),
        face("isearch", foreground=mode["search"]["current_foreground"], background=mode["search"]["current_background"], weight="bold"),
        face("isearch-fail", foreground=mode["diagnostic"]["error"], background=mode["diff"]["delete"], underline=True),
        face("show-paren-match", foreground=mode["match"]["foreground"], background=mode["match"]["background"], weight="bold"),
        face("show-paren-mismatch", foreground=mode["diagnostic"]["error"], background=mode["diff"]["delete"], underline=True),
        face("trailing-whitespace", foreground=mode["diagnostic"]["error"], background=mode["diff"]["delete"]),
        face("escape-glyph", foreground=mode["rust"]),
        face("homoglyph", foreground=mode["violet"]),
        face("nobreak-space", foreground=mode["diagnostic"]["warning"], underline=True),
        face("tooltip", foreground=mode["foreground"]["primary"], background=mode["surface"]["floating"]),
        face("completions-common-part", foreground=mode["blue_ink"]["bright"], weight="bold"),
        face("completions-first-difference", foreground=mode["teal"]["primary"], weight="bold"),
        face("font-lock-bracket-face", foreground=mode["graphite"]),
        face("font-lock-builtin-face", foreground=mode["violet"]),
        face("font-lock-comment-delimiter-face", foreground=mode["foreground"]["muted"], slant="italic"),
        face("font-lock-comment-face", foreground=mode["foreground"]["muted"], slant="italic"),
        face("font-lock-constant-face", foreground=mode["amber"]),
        face("font-lock-delimiter-face", foreground=mode["graphite"]),
        face("font-lock-doc-face", foreground=mode["foreground"]["muted"]),
        face("font-lock-doc-markup-face", foreground=mode["sepia"]),
        face("font-lock-escape-face", foreground=mode["rust"]),
        face("font-lock-function-call-face", foreground=mode["blue_ink"]["bright"], weight="bold"),
        face("font-lock-function-name-face", foreground=mode["blue_ink"]["bright"], weight="bold"),
        face("font-lock-keyword-face", foreground=mode["blue_ink"]["deep"], weight="bold"),
        face("font-lock-misc-punctuation-face", foreground=mode["graphite"]),
        face("font-lock-negation-char-face", foreground=mode["burgundy"], weight="bold"),
        face("font-lock-number-face", foreground=mode["amber"]),
        face("font-lock-operator-face", foreground=mode["graphite"]),
        face("font-lock-preprocessor-face", foreground=mode["violet"]),
        face("font-lock-property-name-face", foreground=mode["sepia"]),
        face("font-lock-property-use-face", foreground=mode["sepia"]),
        face("font-lock-punctuation-face", foreground=mode["graphite"]),
        face("font-lock-regexp-face", foreground=mode["rust"]),
        face("font-lock-regexp-grouping-backslash", foreground=mode["rust"], weight="bold"),
        face("font-lock-regexp-grouping-construct", foreground=mode["violet"], weight="bold"),
        face("font-lock-string-face", foreground=mode["teal"]["primary"]),
        face("font-lock-type-face", foreground=mode["moss"]["primary"], weight="bold"),
        face("font-lock-variable-name-face", foreground=mode["foreground"]["primary"]),
        face("font-lock-variable-use-face", foreground=mode["foreground"]["primary"]),
        face("font-lock-warning-face", foreground=mode["diagnostic"]["error"], weight="bold", underline=True),
        face("diff-added", foreground=mode["diff"]["foreground"], background=mode["diff"]["add"], extend=True),
        face("diff-changed", foreground=mode["diff"]["foreground"], background=mode["diff"]["change"], extend=True),
        face("diff-removed", foreground=mode["diff"]["foreground"], background=mode["diff"]["delete"], extend=True),
        face("diff-refine-added", foreground=mode["diff"]["foreground"], background=mode["diff"]["add_text"], weight="bold"),
        face("diff-refine-changed", foreground=mode["diff"]["foreground"], background=mode["diff"]["change_text"], weight="bold"),
        face("diff-refine-removed", foreground=mode["diff"]["foreground"], background=mode["diff"]["delete_text"], weight="bold"),
        face("diff-file-header", foreground=mode["blue_ink"]["deep"], background=mode["surface"]["subtle"], weight="bold"),
        face("diff-header", foreground=mode["foreground"]["secondary"], background=mode["surface"]["elevated"]),
        face("diff-hunk-header", foreground=mode["violet"], background=mode["surface"]["subtle"]),
        face("flymake-error", foreground=mode["diagnostic"]["error"], underline=True),
        face("flymake-warning", foreground=mode["diagnostic"]["warning"], underline=True),
        face("flymake-note", foreground=mode["diagnostic"]["hint"], underline=True),
        face("flycheck-error", foreground=mode["diagnostic"]["error"], underline=True),
        face("flycheck-warning", foreground=mode["diagnostic"]["warning"], underline=True),
        face("flycheck-info", foreground=mode["diagnostic"]["information"], underline=True),
        face("compilation-error", foreground=mode["diagnostic"]["error"], weight="bold"),
        face("compilation-warning", foreground=mode["diagnostic"]["warning"], weight="bold"),
        face("compilation-info", foreground=mode["diagnostic"]["information"]),
        face("compilation-line-number", foreground=mode["amber"]),
        face("dired-directory", foreground=mode["blue_ink"]["primary"], weight="bold"),
        face("dired-flagged", foreground=mode["diagnostic"]["error"], weight="bold"),
        face("dired-marked", foreground=mode["diagnostic"]["warning"], weight="bold"),
        face("dired-symlink", foreground=mode["teal"]["primary"]),
        face("org-level-1", foreground=mode["blue_ink"]["deep"], weight="bold"),
        face("org-level-2", foreground=mode["moss"]["primary"], weight="bold"),
        face("org-level-3", foreground=mode["blue_ink"]["bright"], weight="bold"),
        face("org-level-4", foreground=mode["amber"], weight="bold"),
        face("org-block", foreground=mode["foreground"]["secondary"], background=mode["surface"]["elevated"]),
        face("org-block-begin-line", foreground=mode["foreground"]["muted"], background=mode["surface"]["subtle"]),
        face("org-code", foreground=mode["teal"]["primary"]),
        face("org-date", foreground=mode["hyperlink"], underline=True),
        face("org-done", foreground=mode["diagnostic"]["success"], weight="bold"),
        face("org-todo", foreground=mode["diagnostic"]["warning"], weight="bold"),
        face("markdown-header-face-1", foreground=mode["blue_ink"]["deep"], weight="bold"),
        face("markdown-header-face-2", foreground=mode["moss"]["primary"], weight="bold"),
        face("markdown-header-face-3", foreground=mode["blue_ink"]["bright"], weight="bold"),
        face("markdown-code-face", foreground=mode["teal"]["primary"], background=mode["surface"]["elevated"]),
        face("markdown-link-face", foreground=mode["hyperlink"], underline=True),
        face("markdown-url-face", foreground=mode["foreground"]["muted"], underline=True),
        face("tab-bar", foreground=mode["foreground"]["muted"], background=mode["surface"]["elevated"]),
        face("tab-bar-tab", foreground=mode["blue_ink"]["deep"], background=mode["surface"]["subtle"], weight="bold"),
        face("tab-bar-tab-inactive", foreground=mode["foreground"]["muted"], background=mode["surface"]["elevated"]),
        face("tab-line", foreground=mode["foreground"]["muted"], background=mode["surface"]["elevated"]),
        face("tab-line-tab-current", foreground=mode["blue_ink"]["deep"], background=mode["surface"]["subtle"], weight="bold"),
        face("company-tooltip", foreground=mode["foreground"]["primary"], background=mode["surface"]["elevated"]),
        face("company-tooltip-selection", foreground=mode["selection"]["foreground"], background=mode["selection"]["background"], weight="bold"),
        face("company-tooltip-common", foreground=mode["blue_ink"]["bright"], weight="bold"),
        face("corfu-default", foreground=mode["foreground"]["primary"], background=mode["surface"]["elevated"]),
        face("corfu-current", foreground=mode["selection"]["foreground"], background=mode["selection"]["background"], weight="bold"),
        face("vertico-current", foreground=mode["selection"]["foreground"], background=mode["selection"]["background"], weight="bold"),
        face("consult-highlight-match", foreground=mode["blue_ink"]["bright"], weight="bold"),
        face("magit-section-heading", foreground=mode["blue_ink"]["deep"], weight="bold"),
        face("magit-section-highlight", background=mode["current_line"], extend=True),
        face("magit-diff-added", foreground=mode["diff"]["foreground"], background=mode["diff"]["add"], extend=True),
        face("magit-diff-removed", foreground=mode["diff"]["foreground"], background=mode["diff"]["delete"], extend=True),
        face("magit-branch-local", foreground=mode["moss"]["primary"], weight="bold"),
        face("magit-branch-remote", foreground=mode["teal"]["primary"], weight="bold"),
    ]
    ansi = [entry["hex"] for entry in mode["ansi"]]
    ansi_names = ("black", "red", "green", "yellow", "blue", "magenta", "cyan", "white")
    for index, name in enumerate(ansi_names):
        faces.append(face(f"term-color-{name}", foreground=ansi[index], background=ansi[index]))
        faces.append(face(f"ansi-color-{name}", foreground=ansi[index], background=ansi[index]))
        faces.append(face(f"ansi-color-bright-{name}", foreground=ansi[index + 8], background=ansi[index + 8]))

    normal_vector = " ".join(json.dumps(color) for color in ansi[:8])
    terminal_vector = " ".join(["unspecified", *(json.dumps(color) for color in ansi[:8])])
    return (
        f";;; {theme}-theme.el --- Nib {style} colour theme -*- lexical-binding: t; -*-\n\n"
        f";; {MARKER}\n"
        ";; Package-Requires: ((emacs \"27.1\"))\n"
        ";; Keywords: faces, theme\n\n"
        f"(deftheme {theme}\n  \"Nib {style}: fountain-pen ink on {'warm ivory' if style == 'light' else 'near-black navy'} paper.\")\n\n"
        "(custom-theme-set-faces\n"
        f" '{theme}\n"
        + "\n".join(faces)
        + ")\n\n"
        "(custom-theme-set-variables\n"
        f" '{theme}\n"
        f" '(ansi-color-names-vector [{normal_vector}])\n"
        f" '(ansi-term-color-vector [{terminal_vector}]))\n\n"
        f"(provide-theme '{theme})\n\n"
        f";;; {theme}-theme.el ends here\n"
    )


def vscode_colors(mode: dict[str, Any]) -> dict[str, str]:
    ansi = [entry["hex"] for entry in mode["ansi"]]
    colors = {
        "foreground": mode["foreground"]["primary"],
        "disabledForeground": mode["foreground"]["disabled"],
        "focusBorder": mode["border"]["focus"],
        "descriptionForeground": mode["foreground"]["muted"],
        "errorForeground": mode["diagnostic"]["error"],
        "icon.foreground": mode["foreground"]["secondary"],
        "selection.background": mode["selection"]["background"],
        "textLink.foreground": mode["hyperlink"],
        "textLink.activeForeground": mode["blue_ink"]["bright"],
        "textPreformat.foreground": mode["teal"]["primary"],
        "textBlockQuote.background": mode["surface"]["elevated"],
        "textBlockQuote.border": mode["border"]["default"],
        "textCodeBlock.background": mode["surface"]["elevated"],
        "button.foreground": mode["background"],
        "button.background": mode["blue_ink"]["primary"],
        "button.hoverBackground": mode["blue_ink"]["deep"],
        "button.secondaryForeground": mode["foreground"]["primary"],
        "button.secondaryBackground": mode["surface"]["subtle"],
        "button.secondaryHoverBackground": mode["selection"]["background"],
        "checkbox.background": mode["surface"]["floating"],
        "checkbox.foreground": mode["foreground"]["primary"],
        "checkbox.border": mode["border"]["default"],
        "dropdown.background": mode["surface"]["floating"],
        "dropdown.foreground": mode["foreground"]["primary"],
        "dropdown.border": mode["border"]["default"],
        "input.background": mode["surface"]["floating"],
        "input.foreground": mode["foreground"]["primary"],
        "input.border": mode["border"]["default"],
        "input.placeholderForeground": mode["foreground"]["muted"],
        "inputOption.activeBackground": mode["selection"]["background"],
        "inputOption.activeForeground": mode["selection"]["foreground"],
        "inputOption.activeBorder": mode["border"]["focus"],
        "inputValidation.errorBackground": mode["diff"]["delete"],
        "inputValidation.errorForeground": mode["diagnostic"]["error"],
        "inputValidation.errorBorder": mode["diagnostic"]["error"],
        "inputValidation.warningBackground": mode["surface"]["subtle"],
        "inputValidation.warningForeground": mode["diagnostic"]["warning"],
        "inputValidation.warningBorder": mode["diagnostic"]["warning"],
        "inputValidation.infoBackground": mode["diff"]["change"],
        "inputValidation.infoForeground": mode["diagnostic"]["information"],
        "inputValidation.infoBorder": mode["diagnostic"]["information"],
        "badge.foreground": mode["background"],
        "badge.background": mode["blue_ink"]["primary"],
        "progressBar.background": mode["blue_ink"]["bright"],
        "scrollbarSlider.background": mode["border"]["subtle"],
        "scrollbarSlider.hoverBackground": mode["border"]["default"],
        "scrollbarSlider.activeBackground": mode["border"]["focus"],
        "list.activeSelectionBackground": mode["selection"]["background"],
        "list.activeSelectionForeground": mode["selection"]["foreground"],
        "list.inactiveSelectionBackground": mode["match"]["background"],
        "list.inactiveSelectionForeground": mode["match"]["foreground"],
        "list.hoverBackground": mode["current_line"],
        "list.focusBackground": mode["selection"]["background"],
        "list.focusForeground": mode["selection"]["foreground"],
        "list.highlightForeground": mode["blue_ink"]["bright"],
        "list.errorForeground": mode["diagnostic"]["error"],
        "list.warningForeground": mode["diagnostic"]["warning"],
        "activityBar.background": mode["surface"]["elevated"],
        "activityBar.foreground": mode["blue_ink"]["deep"],
        "activityBar.inactiveForeground": mode["foreground"]["muted"],
        "activityBar.border": mode["border"]["subtle"],
        "activityBar.activeBorder": mode["border"]["focus"],
        "activityBarBadge.background": mode["moss"]["primary"],
        "activityBarBadge.foreground": mode["background"],
        "sideBar.background": mode["surface"]["elevated"],
        "sideBar.foreground": mode["foreground"]["secondary"],
        "sideBar.border": mode["border"]["subtle"],
        "sideBarTitle.foreground": mode["blue_ink"]["deep"],
        "sideBarSectionHeader.background": mode["surface"]["subtle"],
        "sideBarSectionHeader.foreground": mode["foreground"]["primary"],
        "sideBarSectionHeader.border": mode["border"]["subtle"],
        "editorGroup.border": mode["border"]["default"],
        "editorGroupHeader.tabsBackground": mode["surface"]["elevated"],
        "editorGroupHeader.noTabsBackground": mode["surface"]["elevated"],
        "editorGroupHeader.border": mode["border"]["subtle"],
        "tab.activeBackground": mode["background"],
        "tab.activeForeground": mode["foreground"]["primary"],
        "tab.inactiveBackground": mode["surface"]["elevated"],
        "tab.inactiveForeground": mode["foreground"]["muted"],
        "tab.activeBorderTop": mode["border"]["focus"],
        "tab.border": mode["border"]["subtle"],
        "tab.unfocusedActiveForeground": mode["foreground"]["secondary"],
        "tab.unfocusedInactiveForeground": mode["foreground"]["disabled"],
        "editor.background": mode["background"],
        "editor.foreground": mode["foreground"]["primary"],
        "editorLineNumber.foreground": mode["foreground"]["disabled"],
        "editorLineNumber.activeForeground": mode["blue_ink"]["bright"],
        "editorCursor.foreground": mode["cursor"]["background"],
        "editorCursor.background": mode["cursor"]["foreground"],
        "editor.selectionBackground": mode["selection"]["background"],
        "editor.selectionForeground": mode["selection"]["foreground"],
        "editor.inactiveSelectionBackground": mode["match"]["background"],
        "editor.selectionHighlightBackground": mode["match"]["background"],
        "editor.wordHighlightBackground": mode["match"]["background"],
        "editor.wordHighlightStrongBackground": mode["diff"]["change_text"],
        "editor.findMatchBackground": mode["search"]["current_background"],
        "editor.findMatchForeground": mode["search"]["current_foreground"],
        "editor.findMatchHighlightBackground": mode["search"]["background"],
        "editor.findMatchHighlightForeground": mode["search"]["foreground"],
        "editor.findRangeHighlightBackground": mode["surface"]["subtle"],
        "editor.hoverHighlightBackground": mode["match"]["background"],
        "editor.lineHighlightBackground": mode["current_line"],
        "editor.lineHighlightBorder": mode["border"]["subtle"],
        "editorLink.activeForeground": mode["hyperlink"],
        "editorWhitespace.foreground": mode["border"]["subtle"],
        "editorIndentGuide.background1": mode["border"]["subtle"],
        "editorIndentGuide.activeBackground1": mode["border"]["default"],
        "editorRuler.foreground": mode["border"]["subtle"],
        "editorCodeLens.foreground": mode["foreground"]["muted"],
        "editorInlayHint.foreground": mode["foreground"]["muted"],
        "editorInlayHint.background": mode["surface"]["subtle"],
        "editorBracketMatch.background": mode["match"]["background"],
        "editorBracketMatch.border": mode["border"]["focus"],
        "editorBracketHighlight.foreground1": mode["blue_ink"]["primary"],
        "editorBracketHighlight.foreground2": mode["moss"]["primary"],
        "editorBracketHighlight.foreground3": mode["teal"]["primary"],
        "editorBracketHighlight.foreground4": mode["burgundy"],
        "editorBracketHighlight.foreground5": mode["violet"],
        "editorBracketHighlight.foreground6": mode["amber"],
        "editorError.foreground": mode["diagnostic"]["error"],
        "editorWarning.foreground": mode["diagnostic"]["warning"],
        "editorInfo.foreground": mode["diagnostic"]["information"],
        "editorHint.foreground": mode["diagnostic"]["hint"],
        "editorGutter.background": mode["background"],
        "editorGutter.addedBackground": mode["diagnostic"]["success"],
        "editorGutter.modifiedBackground": mode["diagnostic"]["information"],
        "editorGutter.deletedBackground": mode["diagnostic"]["error"],
        "diffEditor.insertedTextBackground": mode["diff"]["add_text"],
        "diffEditor.removedTextBackground": mode["diff"]["delete_text"],
        "diffEditor.insertedLineBackground": mode["diff"]["add"],
        "diffEditor.removedLineBackground": mode["diff"]["delete"],
        "diffEditor.diagonalFill": mode["border"]["subtle"],
        "editorWidget.foreground": mode["foreground"]["primary"],
        "editorWidget.background": mode["surface"]["floating"],
        "editorWidget.border": mode["border"]["default"],
        "editorSuggestWidget.background": mode["surface"]["elevated"],
        "editorSuggestWidget.foreground": mode["foreground"]["primary"],
        "editorSuggestWidget.border": mode["border"]["default"],
        "editorSuggestWidget.selectedBackground": mode["selection"]["background"],
        "editorSuggestWidget.selectedForeground": mode["selection"]["foreground"],
        "editorSuggestWidget.highlightForeground": mode["blue_ink"]["bright"],
        "editorHoverWidget.background": mode["surface"]["floating"],
        "editorHoverWidget.foreground": mode["foreground"]["primary"],
        "editorHoverWidget.border": mode["border"]["default"],
        "peekView.border": mode["border"]["focus"],
        "peekViewEditor.background": mode["surface"]["floating"],
        "peekViewResult.background": mode["surface"]["elevated"],
        "peekViewResult.selectionBackground": mode["selection"]["background"],
        "peekViewResult.selectionForeground": mode["selection"]["foreground"],
        "peekViewTitle.background": mode["surface"]["subtle"],
        "peekViewTitleLabel.foreground": mode["blue_ink"]["deep"],
        "panel.background": mode["surface"]["elevated"],
        "panel.border": mode["border"]["default"],
        "panelTitle.activeForeground": mode["foreground"]["primary"],
        "panelTitle.inactiveForeground": mode["foreground"]["muted"],
        "panelTitle.activeBorder": mode["border"]["focus"],
        "statusBar.background": mode["surface"]["subtle"],
        "statusBar.foreground": mode["foreground"]["primary"],
        "statusBar.border": mode["border"]["subtle"],
        "statusBar.noFolderBackground": mode["surface"]["elevated"],
        "statusBar.debuggingBackground": mode["rust"],
        "statusBar.debuggingForeground": mode["background"],
        "titleBar.activeBackground": mode["surface"]["elevated"],
        "titleBar.activeForeground": mode["foreground"]["primary"],
        "titleBar.inactiveBackground": mode["surface"]["elevated"],
        "titleBar.inactiveForeground": mode["foreground"]["muted"],
        "titleBar.border": mode["border"]["subtle"],
        "menu.background": mode["surface"]["floating"],
        "menu.foreground": mode["foreground"]["primary"],
        "menu.selectionBackground": mode["selection"]["background"],
        "menu.selectionForeground": mode["selection"]["foreground"],
        "menu.separatorBackground": mode["border"]["subtle"],
        "breadcrumb.foreground": mode["foreground"]["muted"],
        "breadcrumb.focusForeground": mode["foreground"]["primary"],
        "breadcrumb.activeSelectionForeground": mode["blue_ink"]["bright"],
        "breadcrumbPicker.background": mode["surface"]["floating"],
        "gitDecoration.addedResourceForeground": mode["diagnostic"]["success"],
        "gitDecoration.modifiedResourceForeground": mode["diagnostic"]["information"],
        "gitDecoration.deletedResourceForeground": mode["diagnostic"]["error"],
        "gitDecoration.renamedResourceForeground": mode["teal"]["primary"],
        "gitDecoration.untrackedResourceForeground": mode["moss"]["muted"],
        "gitDecoration.ignoredResourceForeground": mode["foreground"]["disabled"],
        "gitDecoration.conflictingResourceForeground": mode["diagnostic"]["warning"],
        "terminal.background": mode["background"],
        "terminal.foreground": mode["foreground"]["primary"],
        "terminalCursor.foreground": mode["cursor"]["background"],
        "terminalCursor.background": mode["cursor"]["foreground"],
        "terminal.selectionBackground": mode["selection"]["background"],
    }
    for index, name in enumerate(("Black", "Red", "Green", "Yellow", "Blue", "Magenta", "Cyan", "White")):
        colors[f"terminal.ansi{name}"] = ansi[index]
        colors[f"terminal.ansiBright{name}"] = ansi[index + 8]
    return colors


def vscode_token_colors(mode: dict[str, Any]) -> list[dict[str, Any]]:
    return [
        {"name": "Plain text", "scope": ["source", "text.html.markdown"], "settings": {"foreground": mode["foreground"]["primary"]}},
        {"name": "Comments", "scope": ["comment", "punctuation.definition.comment"], "settings": {"foreground": mode["foreground"]["muted"], "fontStyle": "italic"}},
        {"name": "Strings", "scope": ["string", "string.quoted", "markup.inline.raw"], "settings": {"foreground": mode["teal"]["primary"]}},
        {"name": "Escapes and regular expressions", "scope": ["constant.character.escape", "string.regexp", "constant.regexp"], "settings": {"foreground": mode["rust"]}},
        {"name": "Numbers and constants", "scope": ["constant.numeric", "constant.other", "support.constant"], "settings": {"foreground": mode["amber"]}},
        {"name": "Booleans", "scope": ["constant.language.boolean", "constant.language.null"], "settings": {"foreground": mode["burgundy"], "fontStyle": "bold"}},
        {"name": "Functions and methods", "scope": ["entity.name.function", "entity.name.method", "support.function", "meta.function-call variable.function"], "settings": {"foreground": mode["blue_ink"]["bright"], "fontStyle": "bold"}},
        {"name": "Types and classes", "scope": ["entity.name.type", "entity.name.class", "support.type", "support.class", "storage.type"], "settings": {"foreground": mode["moss"]["primary"], "fontStyle": "bold"}},
        {"name": "Keywords", "scope": ["keyword", "storage.modifier"], "settings": {"foreground": mode["blue_ink"]["deep"], "fontStyle": "bold"}},
        {"name": "Control flow", "scope": ["keyword.control", "keyword.control.flow", "keyword.control.conditional", "keyword.control.loop"], "settings": {"foreground": mode["burgundy"], "fontStyle": "bold"}},
        {"name": "Storage and declarations", "scope": ["storage.type", "storage.modifier"], "settings": {"foreground": mode["moss"]["primary"]}},
        {"name": "Operators", "scope": ["keyword.operator", "punctuation.separator", "punctuation.terminator"], "settings": {"foreground": mode["graphite"]}},
        {"name": "Preprocessor and attributes", "scope": ["meta.preprocessor", "keyword.control.directive", "entity.name.function.preprocessor"], "settings": {"foreground": mode["violet"]}},
        {"name": "Tags", "scope": ["entity.name.tag", "punctuation.definition.tag"], "settings": {"foreground": mode["moss"]["primary"]}},
        {"name": "Properties and attributes", "scope": ["variable.other.property", "support.type.property-name", "entity.other.attribute-name"], "settings": {"foreground": mode["sepia"]}},
        {"name": "Variables and parameters", "scope": ["variable", "variable.parameter"], "settings": {"foreground": mode["foreground"]["primary"]}},
        {"name": "Invalid", "scope": ["invalid", "invalid.illegal"], "settings": {"foreground": mode["diagnostic"]["error"], "fontStyle": "underline"}},
        {"name": "Deprecated", "scope": ["invalid.deprecated", "entity.other.attribute-name.deprecated"], "settings": {"foreground": mode["foreground"]["disabled"], "fontStyle": "strikethrough"}},
        {"name": "Markup headings", "scope": ["markup.heading", "entity.name.section"], "settings": {"foreground": mode["blue_ink"]["deep"], "fontStyle": "bold"}},
        {"name": "Markup links", "scope": ["markup.underline.link", "string.other.link"], "settings": {"foreground": mode["hyperlink"], "fontStyle": "underline"}},
        {"name": "Markup quote", "scope": ["markup.quote"], "settings": {"foreground": mode["foreground"]["muted"], "fontStyle": "italic"}},
        {"name": "Markup inserted", "scope": ["markup.inserted"], "settings": {"foreground": mode["diagnostic"]["success"]}},
        {"name": "Markup changed", "scope": ["markup.changed"], "settings": {"foreground": mode["diagnostic"]["information"]}},
        {"name": "Markup deleted", "scope": ["markup.deleted"], "settings": {"foreground": mode["diagnostic"]["error"]}},
    ]


def vscode_semantic_colors(mode: dict[str, Any]) -> dict[str, Any]:
    return {
        "namespace": mode["moss"]["muted"],
        "type": {"foreground": mode["moss"]["primary"], "bold": True},
        "class": {"foreground": mode["moss"]["primary"], "bold": True},
        "enum": {"foreground": mode["moss"]["primary"], "bold": True},
        "interface": {"foreground": mode["moss"]["primary"], "bold": True},
        "struct": {"foreground": mode["moss"]["primary"], "bold": True},
        "typeParameter": {"foreground": mode["moss"]["muted"], "bold": True},
        "function": {"foreground": mode["blue_ink"]["bright"], "bold": True},
        "method": {"foreground": mode["blue_ink"]["bright"], "bold": True},
        "macro": {"foreground": mode["violet"], "bold": True},
        "label": mode["moss"]["primary"],
        "variable": mode["foreground"]["primary"],
        "parameter": mode["foreground"]["secondary"],
        "property": mode["sepia"],
        "enumMember": mode["amber"],
        "event": mode["burgundy"],
        "keyword": {"foreground": mode["blue_ink"]["deep"], "bold": True},
        "modifier": mode["moss"]["primary"],
        "comment": {"foreground": mode["foreground"]["muted"], "italic": True},
        "string": mode["teal"]["primary"],
        "number": mode["amber"],
        "regexp": mode["rust"],
        "operator": mode["graphite"],
        "decorator": mode["violet"],
        "*.readonly": {"foreground": mode["amber"], "bold": True},
        "*.deprecated": {"foreground": mode["foreground"]["disabled"], "strikethrough": True},
        "variable.defaultLibrary": mode["violet"],
        "function.defaultLibrary": {"foreground": mode["blue_ink"]["primary"], "underline": True},
        "method.defaultLibrary": {"foreground": mode["blue_ink"]["primary"], "underline": True},
    }


def generated_vscode_theme(style: str, mode: dict[str, Any]) -> str:
    document = {
        "$schema": "vscode://schemas/color-theme",
        "_generated": MARKER,
        "name": f"nib-{style}",
        "semanticHighlighting": True,
        "colors": vscode_colors(mode),
        "tokenColors": vscode_token_colors(mode),
        "semanticTokenColors": vscode_semantic_colors(mode),
    }
    return json.dumps(document, indent=2) + "\n"


def generated_vscode_package(meta: dict[str, Any]) -> str:
    document = {
        "_generated": MARKER,
        "name": "nib-color-theme",
        "displayName": "Nib",
        "description": meta["description"],
        "version": meta["version"],
        "publisher": "local-nib",
        "license": "MIT",
        "repository": {"type": "git", "url": "https://github.com/gongahkia/nib.git"},
        "engines": {"vscode": f"^{meta['minimum_vscode']}"},
        "categories": ["Themes"],
        "keywords": ["theme", "color-theme", "light-theme", "dark-theme", "fountain-pen"],
        "files": ["themes/*.json", "README.md", "LICENSE"],
        "contributes": {
            "themes": [
                {"label": "nib-light", "uiTheme": "vs", "path": "./themes/nib-light-color-theme.json"},
                {"label": "nib-dark", "uiTheme": "vs-dark", "path": "./themes/nib-dark-color-theme.json"},
            ]
        },
    }
    return json.dumps(document, indent=2) + "\n"


def zed_syntax(mode: dict[str, Any]) -> dict[str, dict[str, Any]]:
    def syntax(color: str, *, italic: bool = False, bold: bool = False) -> dict[str, Any]:
        value: dict[str, Any] = {"color": color}
        if italic:
            value["font_style"] = "italic"
        if bold:
            value["font_weight"] = 700
        return value

    return {
        "attribute": syntax(mode["violet"]),
        "boolean": syntax(mode["burgundy"], bold=True),
        "comment": syntax(mode["foreground"]["muted"], italic=True),
        "comment.doc": syntax(mode["foreground"]["muted"]),
        "constant": syntax(mode["amber"]),
        "constructor": syntax(mode["blue_ink"]["bright"], bold=True),
        "embedded": syntax(mode["foreground"]["primary"]),
        "emphasis": syntax(mode["foreground"]["primary"], italic=True),
        "emphasis.strong": syntax(mode["foreground"]["primary"], bold=True),
        "enum": syntax(mode["moss"]["primary"], bold=True),
        "function": syntax(mode["blue_ink"]["bright"], bold=True),
        "hint": syntax(mode["diagnostic"]["hint"]),
        "keyword": syntax(mode["blue_ink"]["deep"], bold=True),
        "label": syntax(mode["moss"]["primary"]),
        "link_text": syntax(mode["hyperlink"]),
        "link_uri": syntax(mode["hyperlink"]),
        "namespace": syntax(mode["moss"]["muted"]),
        "number": syntax(mode["amber"]),
        "operator": syntax(mode["graphite"]),
        "predictive": syntax(mode["foreground"]["disabled"], italic=True),
        "preproc": syntax(mode["violet"]),
        "primary": syntax(mode["foreground"]["primary"]),
        "property": syntax(mode["sepia"]),
        "punctuation": syntax(mode["graphite"]),
        "punctuation.bracket": syntax(mode["graphite"]),
        "punctuation.delimiter": syntax(mode["graphite"]),
        "punctuation.list_marker": syntax(mode["rust"]),
        "punctuation.markup": syntax(mode["rust"]),
        "punctuation.special": syntax(mode["rust"]),
        "selector": syntax(mode["amber"]),
        "selector.pseudo": syntax(mode["violet"]),
        "string": syntax(mode["teal"]["primary"]),
        "string.escape": syntax(mode["rust"]),
        "string.regex": syntax(mode["rust"]),
        "string.special": syntax(mode["violet"]),
        "string.special.symbol": syntax(mode["violet"]),
        "tag": syntax(mode["moss"]["primary"]),
        "text.literal": syntax(mode["teal"]["primary"]),
        "title": syntax(mode["blue_ink"]["deep"], bold=True),
        "type": syntax(mode["moss"]["primary"], bold=True),
        "variable": syntax(mode["foreground"]["primary"]),
        "variable.parameter": syntax(mode["foreground"]["secondary"]),
        "variable.special": syntax(mode["violet"]),
        "variant": syntax(mode["burgundy"]),
        "diff.plus": syntax(mode["diagnostic"]["success"]),
        "diff.minus": syntax(mode["diagnostic"]["error"]),
    }


def zed_style(mode: dict[str, Any]) -> dict[str, Any]:
    ansi = [entry["hex"] for entry in mode["ansi"]]
    style: dict[str, Any] = {
        "background.appearance": "opaque",
        "background": mode["surface"]["elevated"],
        "surface.background": mode["surface"]["elevated"],
        "elevated_surface.background": mode["surface"]["floating"],
        "border": mode["border"]["default"],
        "border.variant": mode["border"]["subtle"],
        "border.focused": mode["border"]["focus"],
        "border.selected": mode["focus"],
        "border.transparent": mode["surface"]["elevated"],
        "border.disabled": mode["border"]["subtle"],
        "element.background": mode["surface"]["elevated"],
        "element.hover": mode["current_line"],
        "element.active": mode["surface"]["subtle"],
        "element.selected": mode["selection"]["background"],
        "element.disabled": mode["surface"]["elevated"],
        "ghost_element.background": mode["surface"]["elevated"],
        "ghost_element.hover": mode["current_line"],
        "ghost_element.active": mode["surface"]["subtle"],
        "ghost_element.selected": mode["selection"]["background"],
        "ghost_element.disabled": mode["surface"]["elevated"],
        "drop_target.background": mode["selection"]["background"],
        "text": mode["foreground"]["primary"],
        "text.muted": mode["foreground"]["muted"],
        "text.placeholder": mode["foreground"]["muted"],
        "text.disabled": mode["foreground"]["disabled"],
        "text.accent": mode["blue_ink"]["bright"],
        "icon": mode["foreground"]["secondary"],
        "icon.muted": mode["foreground"]["muted"],
        "icon.placeholder": mode["foreground"]["muted"],
        "icon.disabled": mode["foreground"]["disabled"],
        "icon.accent": mode["blue_ink"]["bright"],
        "status_bar.background": mode["surface"]["subtle"],
        "title_bar.background": mode["surface"]["elevated"],
        "title_bar.inactive_background": mode["surface"]["elevated"],
        "toolbar.background": mode["background"],
        "tab_bar.background": mode["surface"]["elevated"],
        "tab.inactive_background": mode["surface"]["elevated"],
        "tab.active_background": mode["background"],
        "panel.background": mode["surface"]["elevated"],
        "panel.focused_border": mode["border"]["focus"],
        "pane.focused_border": mode["border"]["focus"],
        "pane_group.border": mode["border"]["default"],
        "panel.indent_guide": mode["border"]["subtle"],
        "panel.indent_guide_active": mode["border"]["default"],
        "panel.indent_guide_hover": mode["border"]["focus"],
        "scrollbar.thumb.background": mode["border"]["subtle"],
        "scrollbar.thumb.hover_background": mode["border"]["default"],
        "scrollbar.thumb.border": mode["border"]["default"],
        "scrollbar.track.background": mode["surface"]["elevated"],
        "scrollbar.track.border": mode["border"]["subtle"],
        "search.match_background": mode["search"]["background"],
        "search.active_match_background": mode["search"]["current_background"],
        "editor.foreground": mode["foreground"]["primary"],
        "editor.background": mode["background"],
        "editor.gutter.background": mode["background"],
        "editor.subheader.background": mode["surface"]["elevated"],
        "editor.active_line.background": mode["current_line"],
        "editor.highlighted_line.background": mode["current_line"],
        "editor.line_number": mode["foreground"]["disabled"],
        "editor.active_line_number": mode["blue_ink"]["bright"],
        "editor.invisible": mode["border"]["subtle"],
        "editor.wrap_guide": mode["border"]["subtle"],
        "editor.active_wrap_guide": mode["border"]["default"],
        "editor.indent_guide": mode["border"]["subtle"],
        "editor.indent_guide_active": mode["border"]["default"],
        "editor.document_highlight.bracket_background": mode["match"]["background"],
        "editor.document_highlight.read_background": mode["match"]["background"],
        "editor.document_highlight.write_background": mode["diff"]["change_text"],
        "conflict": mode["diagnostic"]["warning"],
        "conflict.background": mode["surface"]["subtle"],
        "conflict.border": mode["diagnostic"]["warning"],
        "created": mode["diagnostic"]["success"],
        "created.background": mode["diff"]["add"],
        "created.border": mode["diagnostic"]["success"],
        "deleted": mode["diagnostic"]["error"],
        "deleted.background": mode["diff"]["delete"],
        "deleted.border": mode["diagnostic"]["error"],
        "error": mode["diagnostic"]["error"],
        "error.background": mode["diff"]["delete"],
        "error.border": mode["diagnostic"]["error"],
        "warning": mode["diagnostic"]["warning"],
        "warning.background": mode["surface"]["subtle"],
        "warning.border": mode["diagnostic"]["warning"],
        "info": mode["diagnostic"]["information"],
        "info.background": mode["diff"]["change"],
        "info.border": mode["diagnostic"]["information"],
        "hint": mode["diagnostic"]["hint"],
        "hint.background": mode["diff"]["add"],
        "hint.border": mode["diagnostic"]["hint"],
        "success": mode["diagnostic"]["success"],
        "success.background": mode["diff"]["add"],
        "success.border": mode["diagnostic"]["success"],
        "modified": mode["diagnostic"]["information"],
        "modified.background": mode["diff"]["change"],
        "modified.border": mode["diagnostic"]["information"],
        "renamed": mode["teal"]["primary"],
        "renamed.background": mode["diff"]["change"],
        "renamed.border": mode["teal"]["primary"],
        "hidden": mode["foreground"]["disabled"],
        "hidden.background": mode["surface"]["elevated"],
        "hidden.border": mode["border"]["subtle"],
        "ignored": mode["foreground"]["disabled"],
        "ignored.background": mode["surface"]["elevated"],
        "ignored.border": mode["border"]["subtle"],
        "unreachable": mode["foreground"]["disabled"],
        "unreachable.background": mode["surface"]["elevated"],
        "unreachable.border": mode["border"]["subtle"],
        "predictive": mode["foreground"]["disabled"],
        "predictive.background": mode["surface"]["elevated"],
        "predictive.border": mode["border"]["subtle"],
        "link_text.hover": mode["hyperlink"],
        "version_control.added": mode["diagnostic"]["success"],
        "version_control.modified": mode["diagnostic"]["information"],
        "version_control.deleted": mode["diagnostic"]["error"],
        "version_control.word_added": mode["diff"]["add_text"],
        "version_control.word_deleted": mode["diff"]["delete_text"],
        "terminal.background": mode["background"],
        "terminal.foreground": mode["foreground"]["primary"],
        "terminal.bright_foreground": ansi[15],
        "terminal.dim_foreground": mode["foreground"]["muted"],
        "terminal.ansi.background": mode["background"],
        "players": [
            {"cursor": mode["cursor"]["background"], "background": mode["blue_ink"]["primary"], "selection": mode["selection"]["background"]},
            {"cursor": mode["rust"], "background": mode["rust"], "selection": mode["diff"]["delete_text"]},
            {"cursor": mode["amber"], "background": mode["amber"], "selection": mode["search"]["background"]},
            {"cursor": mode["violet"], "background": mode["violet"], "selection": mode["match"]["background"]},
            {"cursor": mode["teal"]["primary"], "background": mode["teal"]["primary"], "selection": mode["diff"]["change_text"]},
            {"cursor": mode["burgundy"], "background": mode["burgundy"], "selection": mode["diff"]["delete"]},
            {"cursor": mode["moss"]["primary"], "background": mode["moss"]["primary"], "selection": mode["diff"]["add_text"]},
            {"cursor": mode["graphite"], "background": mode["graphite"], "selection": mode["surface"]["subtle"]},
        ],
        "syntax": zed_syntax(mode),
    }
    for index, name in enumerate(("black", "red", "green", "yellow", "blue", "magenta", "cyan", "white")):
        style[f"terminal.ansi.{name}"] = ansi[index]
        style[f"terminal.ansi.bright_{name}"] = ansi[index + 8]
    return style


def generated_zed_theme(palette: dict[str, Any]) -> str:
    document = {
        "$schema": f"https://zed.dev/schema/themes/v{palette['meta']['zed_theme_schema']}.json",
        "_generated": MARKER,
        "name": "nib",
        "author": "nib contributors",
        "themes": [
            {"name": f"nib-{style}", "appearance": style, "style": zed_style(palette["modes"][style])}
            for style in ("light", "dark")
        ],
    }
    return json.dumps(document, indent=2) + "\n"


def generated_zed_manifest(meta: dict[str, Any]) -> str:
    return "\n".join(
        [
            f"# {MARKER}",
            'id = "nib-theme"',
            'name = "nib"',
            f'version = "{meta["version"]}"',
            "schema_version = 1",
            'authors = ["nib contributors"]',
            f'description = "{meta["description"]}"',
            'repository = "https://github.com/gongahkia/nib"',
            "",
        ]
    )


def css_name(path: str) -> str:
    return "--nib-" + path.replace(".", "-").replace("_", "-")


def generated_css(palette: dict[str, Any]) -> str:
    blocks = [f"/* {MARKER} */"]
    for style, mode in palette["modes"].items():
        selector = ":root, [data-theme=\"light\"]" if style == "light" else "[data-theme=\"dark\"]"
        blocks.append(f"{selector} {{")
        for path, color in iter_colors(mode):
            if ".hex" in path:
                continue
            blocks.append(f"  {css_name(path)}: {color};")
        for entry in mode["ansi"]:
            blocks.append(f"  --nib-ansi-{entry['index']}: {entry['hex']};")
        blocks.append("}")
    return "\n".join(blocks) + "\n"


def generated_javascript(palette: dict[str, Any]) -> str:
    data = json.dumps(palette, indent=2, sort_keys=True)
    return f"/* {MARKER} */\nwindow.NIB_PALETTE = {data};\n"


def generated_comparison_javascript() -> str:
    comparisons = json.loads((ROOT / "palette" / "comparisons.json").read_text(encoding="utf-8"))
    data = json.dumps(comparisons, indent=2, sort_keys=True)
    return (
        f"/* {MARKER} */\n"
        "/* Reference values are maintained in palette/comparisons.json. */\n"
        f"window.NIB_COMPARISONS = {data};\n"
    )


def generated_export(palette: dict[str, Any]) -> str:
    export = {
        "generated": MARKER,
        "meta": palette["meta"],
        "modes": {
            style: {
                "roles": {path: color for path, color in iter_colors(mode) if ".hex" not in path},
                "ansi": ansi_colors(mode),
            }
            for style, mode in palette["modes"].items()
        },
    }
    return json.dumps(export, indent=2, sort_keys=True) + "\n"


CONTRAST_PAIRS = (
    ("foreground.primary", "background", 7.0, "principal text"),
    ("foreground.secondary", "background", 4.5, "secondary text"),
    ("foreground.muted", "background", 4.5, "comments/muted text"),
    ("blue_ink.deep", "background", 4.5, "deep blue ink"),
    ("blue_ink.primary", "background", 4.5, "blue ink"),
    ("blue_ink.bright", "background", 4.5, "bright blue ink"),
    ("moss.primary", "background", 4.5, "moss"),
    ("moss.muted", "background", 4.5, "muted moss"),
    ("teal.primary", "background", 4.5, "teal"),
    ("teal.muted", "background", 4.5, "muted teal"),
    ("burgundy", "background", 4.5, "burgundy"),
    ("rust", "background", 4.5, "rust"),
    ("violet", "background", 4.5, "violet"),
    ("amber", "background", 4.5, "amber"),
    ("sepia", "background", 4.5, "sepia"),
    ("graphite", "background", 4.5, "graphite"),
    ("diagnostic.error", "background", 4.5, "error"),
    ("diagnostic.warning", "background", 4.5, "warning"),
    ("diagnostic.information", "background", 4.5, "information"),
    ("diagnostic.hint", "background", 4.5, "hint"),
    ("diagnostic.success", "background", 4.5, "success"),
    ("hyperlink", "background", 4.5, "hyperlink"),
    ("border.default", "background", 3.0, "boundary"),
    ("border.focus", "background", 3.0, "focus boundary"),
    ("selection.foreground", "selection.background", 4.5, "selected text"),
    ("search.foreground", "search.background", 4.5, "search text"),
    ("search.current_foreground", "search.current_background", 4.5, "current search text"),
    ("match.foreground", "match.background", 4.5, "matching text"),
    ("diff.foreground", "diff.add", 4.5, "diff add text"),
    ("diff.foreground", "diff.change", 4.5, "diff change text"),
    ("diff.foreground", "diff.delete", 4.5, "diff delete text"),
    ("cursor.foreground", "cursor.background", 4.5, "cursor text"),
)


def generated_contrast(palette: dict[str, Any]) -> str:
    lines = [
        f"<!-- {MARKER} -->",
        "# Contrast report",
        "",
        "Ratios use WCAG 2 relative luminance on the authored opaque sRGB colors. Passing these targeted checks is not blanket accessibility certification.",
        "",
        "| Mode | Use | Foreground | Background | Ratio | Target | Result |",
        "| --- | --- | --- | --- | ---: | ---: | --- |",
    ]
    for style, mode in palette["modes"].items():
        for foreground_path, background_path, target, label in CONTRAST_PAIRS:
            foreground = get_path(mode, foreground_path)
            background = get_path(mode, background_path)
            ratio = contrast(foreground, background)
            result = "pass" if ratio + 1e-9 >= target else "**FAIL**"
            lines.append(
                f"| {style} | {label} | `{foreground}` | `{background}` | {ratio:.2f}:1 | {target:.1f}:1 | {result} |"
            )
    return "\n".join(lines) + "\n"


def generated_ansi(palette: dict[str, Any]) -> str:
    lines = [
        f"<!-- {MARKER} -->",
        "# ANSI palette",
        "",
        "Indexes retain conventional terminal identities. On the light background, bright variants are optically stronger but are not required to be lighter than their normal partner; this keeps terminal text readable.",
        "",
        "| Index | Identity | Light | Contrast | Dark | Contrast |",
        "| ---: | --- | --- | ---: | --- | ---: |",
    ]
    light = palette["modes"]["light"]
    dark = palette["modes"]["dark"]
    for light_entry, dark_entry in zip(light["ansi"], dark["ansi"]):
        lines.append(
            "| {index} | {name} | `{light}` | {light_ratio:.2f}:1 | `{dark}` | {dark_ratio:.2f}:1 |".format(
                index=light_entry["index"],
                name=light_entry["name"],
                light=light_entry["hex"],
                light_ratio=contrast(light_entry["hex"], light["background"]),
                dark=dark_entry["hex"],
                dark_ratio=contrast(dark_entry["hex"], dark["background"]),
            )
        )
    lines.extend(
        [
            "",
            "ANSI index 0 intentionally remains a low-contrast near-black swatch in dark mode: terminal black is a background/building color, not a general prose color. Indices 1–15 meet the ordinary-text target against the mode background.",
        ]
    )
    return "\n".join(lines) + "\n"


CVD_PAIRS = (
    ("diagnostic.error", "diagnostic.success", "error / success"),
    ("diagnostic.error", "diagnostic.warning", "error / warning"),
    ("blue_ink.primary", "moss.primary", "blue / moss"),
    ("moss.primary", "teal.primary", "moss / teal"),
    ("burgundy", "teal.primary", "burgundy / teal"),
    ("diff.add_text", "diff.delete_text", "diff add / delete tint"),
)


def generated_color_vision(palette: dict[str, Any]) -> str:
    lines = [
        f"<!-- {MARKER} -->",
        "# Colour-vision report",
        "",
        "This deterministic screen uses full-severity linear-sRGB simulation matrices and OKLab distance as a regression signal. It is a design check, not a diagnosis or accessibility certification. Smaller distances mean hues may converge.",
        "",
        "| Mode | Pair | Original | Protanopia | Deuteranopia | Tritanopia |",
        "| --- | --- | ---: | ---: | ---: | ---: |",
    ]
    for style, mode in palette["modes"].items():
        for first_path, second_path, label in CVD_PAIRS:
            first = get_path(mode, first_path)
            second = get_path(mode, second_path)
            values = [oklab_distance(first, second)]
            values.extend(oklab_distance(first, second, name) for name in CVD_MATRICES)
            lines.append(
                f"| {style} | {label} | " + " | ".join(f"{value:.3f}" for value in values) + " |"
            )
    lines.extend(
        [
            "",
            "Hue is never the only carrier of critical state. Diagnostics add `E`/`W`/`I`/`H` gutter signs and severity-specific undercurls; deprecated tokens use strikethrough. Diffs combine signs with separate surface and inline-text tints. Selection and search use distinct backgrounds and current-search contrast.",
        ]
    )
    return "\n".join(lines) + "\n"


def render_files(palette: dict[str, Any]) -> dict[Path, str]:
    files: dict[Path, str] = {
        Path("colors/nib.lua"): generated_entry("auto"),
        Path("colors/nib-light.lua"): generated_entry("light"),
        Path("colors/nib-dark.lua"): generated_entry("dark"),
        Path("ghostty/themes/nib-light"): generated_ghostty("light", palette["modes"]["light"]),
        Path("ghostty/themes/nib-dark"): generated_ghostty("dark", palette["modes"]["dark"]),
        Path("emacs/nib-light-theme.el"): generated_emacs_theme("light", palette["modes"]["light"]),
        Path("emacs/nib-dark-theme.el"): generated_emacs_theme("dark", palette["modes"]["dark"]),
        Path("vscode/package.json"): generated_vscode_package(palette["meta"]),
        Path("vscode/themes/nib-light-color-theme.json"): generated_vscode_theme("light", palette["modes"]["light"]),
        Path("vscode/themes/nib-dark-color-theme.json"): generated_vscode_theme("dark", palette["modes"]["dark"]),
        Path("zed/extension.toml"): generated_zed_manifest(palette["meta"]),
        Path("zed/themes/nib.json"): generated_zed_theme(palette),
        Path("preview/generated/palette.css"): generated_css(palette),
        Path("preview/generated/palette.js"): generated_javascript(palette),
        Path("preview/generated/comparisons.js"): generated_comparison_javascript(),
        Path("dist/nib-palette.json"): generated_export(palette),
        Path("docs/generated/CONTRAST.md"): generated_contrast(palette),
        Path("docs/generated/ANSI.md"): generated_ansi(palette),
        Path("docs/generated/COLOR_VISION.md"): generated_color_vision(palette),
    }
    for style, mode in palette["modes"].items():
        files[Path(f"lua/nib/palette/{style}.lua")] = generated_lua_palette(style, mode)
    return files


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail instead of writing when generated files drift")
    args = parser.parse_args()

    expected = render_files(load_palette(ROOT))
    drift: list[str] = []
    for relative, content in expected.items():
        destination = ROOT / relative
        if args.check:
            if not destination.exists() or destination.read_text(encoding="utf-8") != content:
                drift.append(str(relative))
            continue
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(content, encoding="utf-8")

    if drift:
        print("generated files are missing or stale:", file=sys.stderr)
        for path in drift:
            print(f"  {path}", file=sys.stderr)
        print("run: python3 scripts/generate.py", file=sys.stderr)
        return 1
    if not args.check:
        print(f"generated {len(expected)} files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
