#!/usr/bin/env python3
"""Generate all palette-derived Quireveil assets."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

from theme_utils import CVD_MATRICES, ansi_colors, contrast, get_path, iter_colors, load_palette, oklab_distance

ROOT = Path(__file__).resolve().parents[1]
MARKER = "Generated by scripts/generate.py from palette/palette.json. Do not edit."


def lua_value(value: Any, depth: int = 0) -> str:
    indent = "  " * depth
    child_indent = "  " * (depth + 1)
    if isinstance(value, str):
        return json.dumps(value)
    if isinstance(value, int):
        return str(value)
    if isinstance(value, list):
        if value and isinstance(value[0], dict) and "hex" in value[0]:
            value = [entry["hex"] for entry in value]
        body = ",\n".join(f"{child_indent}{lua_value(child, depth + 1)}" for child in value)
        return "{\n" + body + f"\n{indent}}}"
    if isinstance(value, dict):
        body = ",\n".join(
            f"{child_indent}{key} = {lua_value(child, depth + 1)}" for key, child in value.items()
        )
        return "{\n" + body + f"\n{indent}}}"
    raise TypeError(f"cannot serialize {type(value).__name__} to Lua")


def generated_lua_palette(style: str, mode: dict[str, Any]) -> str:
    runtime_mode = dict(mode)
    runtime_mode["style"] = style
    return f"-- {MARKER}\nreturn {lua_value(runtime_mode)}\n"


def generated_entry(style: str) -> str:
    return (
        f"-- {MARKER}\n"
        f"require(\"quireveil\").load(\"{style}\", \"quireveil{'' if style == 'auto' else '-' + style}\")\n"
    )


def generated_ghostty(style: str, mode: dict[str, Any]) -> str:
    title = f"Quireveil {style.title()}"
    lines = [
        f"# {MARKER}",
        f"# {title} — opaque core theme",
        f"background = {mode['background']}",
        f"foreground = {mode['foreground']['primary']}",
        f"cursor-color = {mode['cursor']['background']}",
        f"cursor-text = {mode['cursor']['foreground']}",
        f"selection-background = {mode['selection']['background']}",
        f"selection-foreground = {mode['selection']['foreground']}",
    ]
    lines.extend(f"palette = {entry['index']}={entry['hex']}" for entry in mode["ansi"])
    return "\n".join(lines) + "\n"


def css_name(path: str) -> str:
    return "--q-" + path.replace(".", "-").replace("_", "-")


def generated_css(palette: dict[str, Any]) -> str:
    blocks = [f"/* {MARKER} */"]
    for style, mode in palette["modes"].items():
        selector = ":root, [data-theme=\"light\"]" if style == "light" else "[data-theme=\"dark\"]"
        blocks.append(f"{selector} {{")
        for path, color in iter_colors(mode):
            if ".hex" in path:
                continue
            blocks.append(f"  {css_name(path)}: {color};")
        for entry in mode["ansi"]:
            blocks.append(f"  --q-ansi-{entry['index']}: {entry['hex']};")
        blocks.append("}")
    return "\n".join(blocks) + "\n"


def generated_javascript(palette: dict[str, Any]) -> str:
    data = json.dumps(palette, indent=2, sort_keys=True)
    return f"/* {MARKER} */\nwindow.QUIREVEIL_PALETTE = {data};\n"


def generated_export(palette: dict[str, Any]) -> str:
    export = {
        "generated": MARKER,
        "meta": palette["meta"],
        "modes": {
            style: {
                "roles": {path: color for path, color in iter_colors(mode) if ".hex" not in path},
                "ansi": ansi_colors(mode),
            }
            for style, mode in palette["modes"].items()
        },
    }
    return json.dumps(export, indent=2, sort_keys=True) + "\n"


CONTRAST_PAIRS = (
    ("foreground.primary", "background", 7.0, "principal text"),
    ("foreground.secondary", "background", 4.5, "secondary text"),
    ("foreground.muted", "background", 4.5, "comments/muted text"),
    ("blue_ink.deep", "background", 4.5, "deep blue ink"),
    ("blue_ink.primary", "background", 4.5, "blue ink"),
    ("blue_ink.bright", "background", 4.5, "bright blue ink"),
    ("moss.primary", "background", 4.5, "moss"),
    ("moss.muted", "background", 4.5, "muted moss"),
    ("teal.primary", "background", 4.5, "teal"),
    ("teal.muted", "background", 4.5, "muted teal"),
    ("burgundy", "background", 4.5, "burgundy"),
    ("rust", "background", 4.5, "rust"),
    ("violet", "background", 4.5, "violet"),
    ("amber", "background", 4.5, "amber"),
    ("sepia", "background", 4.5, "sepia"),
    ("graphite", "background", 4.5, "graphite"),
    ("diagnostic.error", "background", 4.5, "error"),
    ("diagnostic.warning", "background", 4.5, "warning"),
    ("diagnostic.information", "background", 4.5, "information"),
    ("diagnostic.hint", "background", 4.5, "hint"),
    ("diagnostic.success", "background", 4.5, "success"),
    ("hyperlink", "background", 4.5, "hyperlink"),
    ("border.default", "background", 3.0, "boundary"),
    ("border.focus", "background", 3.0, "focus boundary"),
    ("selection.foreground", "selection.background", 4.5, "selected text"),
    ("search.foreground", "search.background", 4.5, "search text"),
    ("search.current_foreground", "search.current_background", 4.5, "current search text"),
    ("match.foreground", "match.background", 4.5, "matching text"),
    ("diff.foreground", "diff.add", 4.5, "diff add text"),
    ("diff.foreground", "diff.change", 4.5, "diff change text"),
    ("diff.foreground", "diff.delete", 4.5, "diff delete text"),
    ("cursor.foreground", "cursor.background", 4.5, "cursor text"),
)


def generated_contrast(palette: dict[str, Any]) -> str:
    lines = [
        f"<!-- {MARKER} -->",
        "# Contrast report",
        "",
        "Ratios use WCAG 2 relative luminance on the authored opaque sRGB colors. Passing these targeted checks is not blanket accessibility certification.",
        "",
        "| Mode | Use | Foreground | Background | Ratio | Target | Result |",
        "| --- | --- | --- | --- | ---: | ---: | --- |",
    ]
    for style, mode in palette["modes"].items():
        for foreground_path, background_path, target, label in CONTRAST_PAIRS:
            foreground = get_path(mode, foreground_path)
            background = get_path(mode, background_path)
            ratio = contrast(foreground, background)
            result = "pass" if ratio + 1e-9 >= target else "**FAIL**"
            lines.append(
                f"| {style} | {label} | `{foreground}` | `{background}` | {ratio:.2f}:1 | {target:.1f}:1 | {result} |"
            )
    return "\n".join(lines) + "\n"


def generated_ansi(palette: dict[str, Any]) -> str:
    lines = [
        f"<!-- {MARKER} -->",
        "# ANSI palette",
        "",
        "Indexes retain conventional terminal identities. On the light background, bright variants are optically stronger but are not required to be lighter than their normal partner; this keeps terminal text readable.",
        "",
        "| Index | Identity | Light | Contrast | Dark | Contrast |",
        "| ---: | --- | --- | ---: | --- | ---: |",
    ]
    light = palette["modes"]["light"]
    dark = palette["modes"]["dark"]
    for light_entry, dark_entry in zip(light["ansi"], dark["ansi"]):
        lines.append(
            "| {index} | {name} | `{light}` | {light_ratio:.2f}:1 | `{dark}` | {dark_ratio:.2f}:1 |".format(
                index=light_entry["index"],
                name=light_entry["name"],
                light=light_entry["hex"],
                light_ratio=contrast(light_entry["hex"], light["background"]),
                dark=dark_entry["hex"],
                dark_ratio=contrast(dark_entry["hex"], dark["background"]),
            )
        )
    lines.extend(
        [
            "",
            "ANSI index 0 intentionally remains a low-contrast near-black swatch in dark mode: terminal black is a background/building color, not a general prose color. Indices 1–15 meet the ordinary-text target against the mode background.",
        ]
    )
    return "\n".join(lines) + "\n"


CVD_PAIRS = (
    ("diagnostic.error", "diagnostic.success", "error / success"),
    ("diagnostic.error", "diagnostic.warning", "error / warning"),
    ("blue_ink.primary", "moss.primary", "blue / moss"),
    ("moss.primary", "teal.primary", "moss / teal"),
    ("burgundy", "teal.primary", "burgundy / teal"),
    ("diff.add_text", "diff.delete_text", "diff add / delete tint"),
)


def generated_color_vision(palette: dict[str, Any]) -> str:
    lines = [
        f"<!-- {MARKER} -->",
        "# Colour-vision report",
        "",
        "This deterministic screen uses full-severity linear-sRGB simulation matrices and OKLab distance as a regression signal. It is a design check, not a diagnosis or accessibility certification. Smaller distances mean hues may converge.",
        "",
        "| Mode | Pair | Original | Protanopia | Deuteranopia | Tritanopia |",
        "| --- | --- | ---: | ---: | ---: | ---: |",
    ]
    for style, mode in palette["modes"].items():
        for first_path, second_path, label in CVD_PAIRS:
            first = get_path(mode, first_path)
            second = get_path(mode, second_path)
            values = [oklab_distance(first, second)]
            values.extend(oklab_distance(first, second, name) for name in CVD_MATRICES)
            lines.append(
                f"| {style} | {label} | " + " | ".join(f"{value:.3f}" for value in values) + " |"
            )
    lines.extend(
        [
            "",
            "Hue is never the only carrier of critical state. Diagnostics add `E`/`W`/`I`/`H` gutter signs and severity-specific undercurls; deprecated tokens use strikethrough. Diffs combine signs with separate surface and inline-text tints. Selection and search use distinct backgrounds and current-search contrast.",
        ]
    )
    return "\n".join(lines) + "\n"


def render_files(palette: dict[str, Any]) -> dict[Path, str]:
    files: dict[Path, str] = {
        Path("colors/quireveil.lua"): generated_entry("auto"),
        Path("colors/quireveil-light.lua"): generated_entry("light"),
        Path("colors/quireveil-dark.lua"): generated_entry("dark"),
        Path("ghostty/themes/Quireveil Light"): generated_ghostty("light", palette["modes"]["light"]),
        Path("ghostty/themes/Quireveil Dark"): generated_ghostty("dark", palette["modes"]["dark"]),
        Path("preview/generated/palette.css"): generated_css(palette),
        Path("preview/generated/palette.js"): generated_javascript(palette),
        Path("dist/quireveil-palette.json"): generated_export(palette),
        Path("docs/generated/CONTRAST.md"): generated_contrast(palette),
        Path("docs/generated/ANSI.md"): generated_ansi(palette),
        Path("docs/generated/COLOR_VISION.md"): generated_color_vision(palette),
    }
    for style, mode in palette["modes"].items():
        files[Path(f"lua/quireveil/palette/{style}.lua")] = generated_lua_palette(style, mode)
    return files


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail instead of writing when generated files drift")
    args = parser.parse_args()

    expected = render_files(load_palette(ROOT))
    drift: list[str] = []
    for relative, content in expected.items():
        destination = ROOT / relative
        if args.check:
            if not destination.exists() or destination.read_text(encoding="utf-8") != content:
                drift.append(str(relative))
            continue
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(content, encoding="utf-8")

    if drift:
        print("generated files are missing or stale:", file=sys.stderr)
        for path in drift:
            print(f"  {path}", file=sys.stderr)
        print("run: python3 scripts/generate.py", file=sys.stderr)
        return 1
    if not args.check:
        print(f"generated {len(expected)} files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
