-- Generated by scripts/generate.py from palette/palette.json. Do not edit.
return {
  background = "#F4EEDC",
  surface = {
    elevated = "#ECE4D2",
    floating = "#FAF6E9",
    subtle = "#E3DAC5"
  },
  border = {
    default = "#877F6E",
    subtle = "#AAA18D",
    focus = "#315D78"
  },
  foreground = {
    primary = "#182A38",
    secondary = "#394B56",
    muted = "#59656A",
    disabled = "#767970"
  },
  blue_ink = {
    deep = "#173B59",
    primary = "#285D7C",
    bright = "#1F668E"
  },
  moss = {
    primary = "#536126",
    muted = "#657038"
  },
  teal = {
    primary = "#17666A",
    muted = "#367375"
  },
  burgundy = "#7C3448",
  rust = "#8A432C",
  violet = "#684873",
  amber = "#77560F",
  sepia = "#705039",
  graphite = "#4F5960",
  diagnostic = {
    error = "#913646",
    warning = "#76540B",
    information = "#285D7C",
    hint = "#17666A",
    success = "#526329"
  },
  selection = {
    background = "#AFC9C3",
    foreground = "#172A38"
  },
  search = {
    background = "#DEC06C",
    foreground = "#2A2B22",
    current_background = "#BD893E",
    current_foreground = "#182A38"
  },
  current_line = "#E8E0CD",
  match = {
    background = "#CAD7B4",
    foreground = "#24372E"
  },
  focus = "#315D78",
  hyperlink = "#1C5F8B",
  diff = {
    add = "#D8E2C3",
    add_text = "#BED29B",
    change = "#D7E1E4",
    change_text = "#B8CDD6",
    delete = "#ECD5D0",
    delete_text = "#DBB6AE",
    foreground = "#263640"
  },
  cursor = {
    background = "#244D68",
    foreground = "#F4EEDC"
  },
  ansi = {
    "#1D2B36",
    "#8D3342",
    "#526126",
    "#76540B",
    "#285D7C",
    "#70446F",
    "#17666A",
    "#4F5960",
    "#5C686E",
    "#A22F42",
    "#62721F",
    "#8A5B00",
    "#176594",
    "#82487B",
    "#006E74",
    "#303F49"
  },
  style = "light"
}
