local M = {}

local function editor_groups(palette, options)
  local normal_background = options.transparent and "NONE" or palette.background
  local noncurrent_background = options.transparent and "NONE" or palette.surface.elevated
  local sign_background = options.transparent and "NONE" or palette.background
  local comment_style = options.italics and { italic = true } or {}

  return {
    Normal = { fg = palette.foreground.primary, bg = normal_background },
    NormalNC = { fg = palette.foreground.secondary, bg = noncurrent_background },
    NormalFloat = { fg = palette.foreground.primary, bg = palette.surface.floating },
    FloatBorder = { fg = palette.border.default, bg = palette.surface.floating },
    FloatTitle = { fg = palette.blue_ink.bright, bg = palette.surface.floating, bold = true },
    FloatFooter = { fg = palette.foreground.muted, bg = palette.surface.floating },
    WinSeparator = { fg = palette.border.default, bg = normal_background },
    VertSplit = { link = "WinSeparator" },
    EndOfBuffer = { fg = normal_background, bg = normal_background },
    NonText = { fg = palette.foreground.disabled },
    Whitespace = { fg = palette.border.subtle },
    SpecialKey = { fg = palette.graphite },
    Conceal = { fg = palette.foreground.disabled },
    Directory = { fg = palette.blue_ink.primary, bold = true },
    Title = { fg = palette.blue_ink.deep, bold = true },
    Question = { fg = palette.moss.primary, bold = true },
    MoreMsg = { fg = palette.moss.primary },
    ModeMsg = { fg = palette.blue_ink.deep, bold = true },
    MsgArea = { fg = palette.foreground.secondary, bg = normal_background },
    MsgSeparator = { fg = palette.border.default, bg = palette.surface.subtle },
    ErrorMsg = { fg = palette.diagnostic.error, bold = true },
    WarningMsg = { fg = palette.diagnostic.warning, bold = true },
    Pmenu = { fg = palette.foreground.primary, bg = palette.surface.elevated },
    PmenuSel = { fg = palette.selection.foreground, bg = palette.selection.background, bold = true },
    PmenuKind = { fg = palette.moss.primary, bg = palette.surface.elevated },
    PmenuKindSel = { fg = palette.moss.primary, bg = palette.selection.background, bold = true },
    PmenuExtra = { fg = palette.foreground.muted, bg = palette.surface.elevated },
    PmenuExtraSel = { fg = palette.selection.foreground, bg = palette.selection.background },
    PmenuMatch = { fg = palette.blue_ink.bright, bg = palette.surface.elevated, bold = true },
    PmenuMatchSel = { fg = palette.blue_ink.deep, bg = palette.selection.background, bold = true },
    PmenuSbar = { bg = palette.surface.subtle },
    PmenuThumb = { bg = palette.border.default },
    WildMenu = { link = "PmenuSel" },
    StatusLine = { fg = palette.foreground.primary, bg = palette.surface.subtle },
    StatusLineNC = { fg = palette.foreground.muted, bg = palette.surface.elevated },
    StatusLineTerm = { link = "StatusLine" },
    StatusLineTermNC = { link = "StatusLineNC" },
    WinBar = { fg = palette.foreground.secondary, bg = normal_background, bold = true },
    WinBarNC = { fg = palette.foreground.muted, bg = noncurrent_background },
    TabLine = { fg = palette.foreground.muted, bg = palette.surface.elevated },
    TabLineFill = { fg = palette.border.subtle, bg = palette.surface.elevated },
    TabLineSel = { fg = palette.blue_ink.deep, bg = palette.surface.subtle, bold = true },
    LineNr = { fg = palette.foreground.disabled, bg = sign_background },
    LineNrAbove = { link = "LineNr" },
    LineNrBelow = { link = "LineNr" },
    CursorLineNr = { fg = palette.blue_ink.bright, bg = palette.current_line, bold = true },
    CursorLineSign = { bg = palette.current_line },
    CursorLineFold = { fg = palette.moss.muted, bg = palette.current_line },
    CursorLine = { bg = palette.current_line },
    CursorColumn = { bg = palette.current_line },
    ColorColumn = { bg = palette.surface.subtle },
    SignColumn = { fg = palette.foreground.muted, bg = sign_background },
    FoldColumn = { fg = palette.moss.muted, bg = sign_background },
    Folded = { fg = palette.foreground.secondary, bg = palette.surface.subtle },
    Cursor = { fg = palette.cursor.foreground, bg = palette.cursor.background },
    lCursor = { link = "Cursor" },
    CursorIM = { link = "Cursor" },
    TermCursor = { link = "Cursor" },
    TermCursorNC = { fg = palette.background, bg = palette.border.default },
    Search = { fg = palette.search.foreground, bg = palette.search.background },
    IncSearch = { fg = palette.search.current_foreground, bg = palette.search.current_background, bold = true },
    CurSearch = { link = "IncSearch" },
    Substitute = { fg = palette.search.current_foreground, bg = palette.search.current_background, bold = true },
    Visual = { fg = palette.selection.foreground, bg = palette.selection.background },
    VisualNOS = { fg = palette.selection.foreground, bg = palette.selection.background, underline = true },
    MatchParen = { fg = palette.match.foreground, bg = palette.match.background, bold = true },
    QuickFixLine = { fg = palette.selection.foreground, bg = palette.selection.background, bold = true },
    qfFileName = { fg = palette.blue_ink.primary },
    qfLineNr = { fg = palette.amber },
    qfError = { fg = palette.diagnostic.error },
    SpellBad = { undercurl = true, sp = palette.diagnostic.error },
    SpellCap = { undercurl = true, sp = palette.diagnostic.information },
    SpellLocal = { undercurl = true, sp = palette.diagnostic.hint },
    SpellRare = { undercurl = true, sp = palette.violet },
    DiffAdd = { fg = palette.diff.foreground, bg = palette.diff.add },
    DiffChange = { fg = palette.diff.foreground, bg = palette.diff.change },
    DiffDelete = { fg = palette.diff.foreground, bg = palette.diff.delete },
    DiffText = { fg = palette.diff.foreground, bg = palette.diff.change_text, bold = true },
    Added = { fg = palette.diagnostic.success },
    Changed = { fg = palette.diagnostic.information },
    Removed = { fg = palette.diagnostic.error },
    diffAdded = { link = "Added" },
    diffChanged = { link = "Changed" },
    diffRemoved = { link = "Removed" },
    diffOldFile = { fg = palette.rust },
    diffNewFile = { fg = palette.moss.primary },
    diffFile = { fg = palette.blue_ink.primary, bold = true },
    diffLine = { fg = palette.violet },
    diffIndexLine = { fg = palette.graphite },
    debugBreakpoint = { fg = palette.diagnostic.error, bold = true },
    debugPC = { bg = palette.diff.change_text },
    Bold = { bold = true },
    Italic = comment_style,
    Underlined = { underline = true },
    Ignore = { fg = palette.foreground.disabled },
    Error = { fg = palette.diagnostic.error, bold = true },
    Todo = { fg = palette.search.current_foreground, bg = palette.search.current_background, bold = true },
  }
end

local function legacy_syntax(palette, options)
  local comment = { fg = palette.foreground.muted }
  if options.italics then
    comment.italic = true
  end
  return {
    Comment = comment,
    Constant = { fg = palette.amber },
    String = { fg = palette.teal.primary },
    Character = { fg = palette.teal.primary },
    Number = { fg = palette.amber },
    Boolean = { fg = palette.burgundy, bold = true },
    Float = { fg = palette.amber },
    Identifier = { fg = palette.foreground.primary },
    Function = { fg = palette.blue_ink.bright, bold = true },
    Statement = { fg = palette.blue_ink.deep, bold = true },
    Conditional = { fg = palette.burgundy, bold = true },
    Repeat = { fg = palette.burgundy, bold = true },
    Label = { fg = palette.moss.primary },
    Operator = { fg = palette.graphite },
    Keyword = { fg = palette.blue_ink.deep, bold = true },
    Exception = { fg = palette.rust, bold = true },
    PreProc = { fg = palette.violet },
    Include = { fg = palette.moss.primary },
    Define = { fg = palette.violet },
    Macro = { fg = palette.violet },
    PreCondit = { fg = palette.violet },
    Type = { fg = palette.moss.primary, bold = true },
    StorageClass = { fg = palette.moss.primary },
    Structure = { fg = palette.moss.primary, bold = true },
    Typedef = { fg = palette.moss.primary },
    Special = { fg = palette.violet },
    SpecialChar = { fg = palette.rust },
    Tag = { fg = palette.moss.primary },
    Delimiter = { fg = palette.graphite },
    SpecialComment = { fg = palette.sepia },
    Debug = { fg = palette.diagnostic.warning },
  }
end

local function treesitter_groups(options)
  return {
    ["@variable"] = { link = "Identifier" },
    ["@variable.builtin"] = { link = "Special" },
    ["@variable.parameter"] = { link = "Identifier" },
    ["@variable.parameter.builtin"] = { link = "Special" },
    ["@variable.member"] = { link = "Identifier" },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { link = "Boolean" },
    ["@constant.macro"] = { link = "Macro" },
    ["@module"] = { link = "Include" },
    ["@module.builtin"] = { link = "Special" },
    ["@label"] = { link = "Label" },
    ["@string"] = { link = "String" },
    ["@string.documentation"] = { link = "Comment" },
    ["@string.regexp"] = { link = "SpecialChar" },
    ["@string.escape"] = { link = "SpecialChar" },
    ["@string.special"] = { link = "Special" },
    ["@string.special.symbol"] = { link = "Special" },
    ["@string.special.path"] = { link = "Directory" },
    ["@string.special.url"] = { link = "Underlined" },
    ["@character"] = { link = "Character" },
    ["@character.special"] = { link = "SpecialChar" },
    ["@boolean"] = { link = "Boolean" },
    ["@number"] = { link = "Number" },
    ["@number.float"] = { link = "Float" },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { link = "Type" },
    ["@type.definition"] = { link = "Typedef" },
    ["@attribute"] = { link = "PreProc" },
    ["@attribute.builtin"] = { link = "Special" },
    ["@property"] = { link = "Identifier" },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { link = "Special" },
    ["@function.call"] = { link = "Function" },
    ["@function.macro"] = { link = "Macro" },
    ["@function.method"] = { link = "Function" },
    ["@function.method.call"] = { link = "Function" },
    ["@constructor"] = { link = "Special" },
    ["@operator"] = { link = "Operator" },
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.coroutine"] = { link = "Conditional" },
    ["@keyword.function"] = { link = "Keyword" },
    ["@keyword.operator"] = { link = "Operator" },
    ["@keyword.import"] = { link = "Include" },
    ["@keyword.type"] = { link = "Type" },
    ["@keyword.modifier"] = { link = "StorageClass" },
    ["@keyword.repeat"] = { link = "Repeat" },
    ["@keyword.return"] = { link = "Conditional" },
    ["@keyword.debug"] = { link = "Debug" },
    ["@keyword.exception"] = { link = "Exception" },
    ["@keyword.conditional"] = { link = "Conditional" },
    ["@keyword.conditional.ternary"] = { link = "Conditional" },
    ["@keyword.directive"] = { link = "PreProc" },
    ["@keyword.directive.define"] = { link = "Define" },
    ["@punctuation.delimiter"] = { link = "Delimiter" },
    ["@punctuation.bracket"] = { link = "Delimiter" },
    ["@punctuation.special"] = { link = "SpecialChar" },
    ["@comment"] = { link = "Comment" },
    ["@comment.documentation"] = { link = "Comment" },
    ["@comment.error"] = { link = "DiagnosticError" },
    ["@comment.warning"] = { link = "DiagnosticWarn" },
    ["@comment.todo"] = { link = "Todo" },
    ["@comment.note"] = { link = "DiagnosticInfo" },
    ["@markup.strong"] = { bold = true },
    ["@markup.italic"] = options.italics and { italic = true } or {},
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.underline"] = { underline = true },
    ["@markup.heading"] = { link = "Title" },
    ["@markup.heading.1"] = { link = "Title" },
    ["@markup.heading.2"] = { link = "Type" },
    ["@markup.heading.3"] = { link = "Function" },
    ["@markup.heading.4"] = { link = "Constant" },
    ["@markup.heading.5"] = { link = "Special" },
    ["@markup.heading.6"] = { link = "Identifier" },
    ["@markup.quote"] = { link = "Comment" },
    ["@markup.math"] = { link = "Special" },
    ["@markup.link"] = { link = "Underlined" },
    ["@markup.link.label"] = { link = "Identifier" },
    ["@markup.link.url"] = { link = "Underlined" },
    ["@markup.raw"] = { link = "String" },
    ["@markup.raw.block"] = { link = "String" },
    ["@markup.list"] = { link = "SpecialChar" },
    ["@markup.list.checked"] = { link = "DiagnosticOk" },
    ["@markup.list.unchecked"] = { link = "DiagnosticWarn" },
    ["@diff.plus"] = { link = "Added" },
    ["@diff.minus"] = { link = "Removed" },
    ["@diff.delta"] = { link = "Changed" },
    ["@tag"] = { link = "Tag" },
    ["@tag.builtin"] = { link = "Special" },
    ["@tag.attribute"] = { link = "Identifier" },
    ["@tag.delimiter"] = { link = "Delimiter" },
  }
end

local function diagnostic_groups(palette)
  return {
    DiagnosticError = { fg = palette.diagnostic.error },
    DiagnosticWarn = { fg = palette.diagnostic.warning },
    DiagnosticInfo = { fg = palette.diagnostic.information },
    DiagnosticHint = { fg = palette.diagnostic.hint },
    DiagnosticOk = { fg = palette.diagnostic.success },
    DiagnosticVirtualTextError = { fg = palette.diagnostic.error, bg = palette.diff.delete },
    DiagnosticVirtualTextWarn = { fg = palette.diagnostic.warning, bg = palette.surface.subtle },
    DiagnosticVirtualTextInfo = { fg = palette.diagnostic.information, bg = palette.diff.change },
    DiagnosticVirtualTextHint = { fg = palette.diagnostic.hint, bg = palette.diff.add },
    DiagnosticVirtualTextOk = { fg = palette.diagnostic.success, bg = palette.diff.add },
    DiagnosticFloatingError = { link = "DiagnosticError" },
    DiagnosticFloatingWarn = { link = "DiagnosticWarn" },
    DiagnosticFloatingInfo = { link = "DiagnosticInfo" },
    DiagnosticFloatingHint = { link = "DiagnosticHint" },
    DiagnosticFloatingOk = { link = "DiagnosticOk" },
    DiagnosticSignError = { fg = palette.diagnostic.error, bold = true },
    DiagnosticSignWarn = { fg = palette.diagnostic.warning, bold = true },
    DiagnosticSignInfo = { fg = palette.diagnostic.information, bold = true },
    DiagnosticSignHint = { fg = palette.diagnostic.hint, bold = true },
    DiagnosticSignOk = { fg = palette.diagnostic.success, bold = true },
    DiagnosticUnderlineError = { undercurl = true, sp = palette.diagnostic.error },
    DiagnosticUnderlineWarn = { undercurl = true, sp = palette.diagnostic.warning },
    DiagnosticUnderlineInfo = { undercurl = true, sp = palette.diagnostic.information },
    DiagnosticUnderlineHint = { undercurl = true, sp = palette.diagnostic.hint },
    DiagnosticUnderlineOk = { undercurl = true, sp = palette.diagnostic.success },
    DiagnosticDeprecated = { strikethrough = true, sp = palette.diagnostic.warning },
    DiagnosticUnnecessary = { fg = palette.foreground.disabled },
    LspReferenceText = { bg = palette.match.background },
    LspReferenceRead = { bg = palette.match.background, underline = true },
    LspReferenceWrite = { bg = palette.diff.change_text, bold = true },
    LspCodeLens = { fg = palette.foreground.muted },
    LspCodeLensSeparator = { fg = palette.border.subtle },
    LspInlayHint = { fg = palette.foreground.muted, bg = palette.surface.subtle },
    LspSignatureActiveParameter = { fg = palette.blue_ink.bright, bold = true },
  }
end

local function semantic_groups(options)
  return {
    ["@lsp.type.class"] = { link = "@type" },
    ["@lsp.type.comment"] = { link = "@comment" },
    ["@lsp.type.decorator"] = { link = "@attribute" },
    ["@lsp.type.enum"] = { link = "@type" },
    ["@lsp.type.enumMember"] = { link = "@constant" },
    ["@lsp.type.event"] = { link = "@constant" },
    ["@lsp.type.function"] = { link = "@function" },
    ["@lsp.type.interface"] = { link = "@type" },
    ["@lsp.type.keyword"] = { link = "@keyword" },
    ["@lsp.type.macro"] = { link = "@function.macro" },
    ["@lsp.type.method"] = { link = "@function.method" },
    ["@lsp.type.modifier"] = { link = "@keyword.modifier" },
    ["@lsp.type.namespace"] = { link = "@module" },
    ["@lsp.type.number"] = { link = "@number" },
    ["@lsp.type.operator"] = { link = "@operator" },
    ["@lsp.type.parameter"] = { link = "@variable.parameter" },
    ["@lsp.type.property"] = { link = "@property" },
    ["@lsp.type.regexp"] = { link = "@string.regexp" },
    ["@lsp.type.string"] = { link = "@string" },
    ["@lsp.type.struct"] = { link = "@type" },
    ["@lsp.type.type"] = { link = "@type" },
    ["@lsp.type.typeParameter"] = { link = "@type.definition" },
    ["@lsp.type.variable"] = { link = "@variable" },
    ["@lsp.mod.deprecated"] = { strikethrough = true },
    ["@lsp.mod.readonly"] = { bold = true },
    ["@lsp.mod.documentation"] = options.italics and { italic = true } or {},
    ["@lsp.mod.defaultLibrary"] = { underline = true },
    ["@lsp.typemod.variable.readonly"] = { link = "@constant" },
    ["@lsp.typemod.property.readonly"] = { link = "@constant" },
    ["@lsp.typemod.variable.defaultLibrary"] = { link = "@variable.builtin" },
    ["@lsp.typemod.function.defaultLibrary"] = { link = "@function.builtin" },
    ["@lsp.typemod.method.defaultLibrary"] = { link = "@function.builtin" },
    ["@lsp.typemod.class.defaultLibrary"] = { link = "@type.builtin" },
    ["@lsp.typemod.function.async"] = { link = "@function" },
    ["@lsp.typemod.method.async"] = { link = "@function.method" },
  }
end

local function markdown_and_help()
  return {
    markdownH1 = { link = "@markup.heading.1" },
    markdownH2 = { link = "@markup.heading.2" },
    markdownH3 = { link = "@markup.heading.3" },
    markdownHeadingDelimiter = { link = "Delimiter" },
    markdownCode = { link = "String" },
    markdownCodeBlock = { link = "String" },
    markdownLinkText = { link = "Underlined" },
    markdownUrl = { link = "Underlined" },
    markdownBlockquote = { link = "Comment" },
    markdownListMarker = { link = "SpecialChar" },
    helpCommand = { link = "String" },
    helpExample = { link = "String" },
    helpHeader = { link = "Title" },
    helpHyperTextEntry = { link = "Underlined" },
    helpHyperTextJump = { link = "Underlined" },
    helpOption = { link = "Type" },
    helpSectionDelim = { link = "Delimiter" },
    helpSpecial = { link = "Special" },
  }
end

function M.groups(palette, options)
  return vim.tbl_extend(
    "force",
    editor_groups(palette, options),
    legacy_syntax(palette, options),
    treesitter_groups(options),
    diagnostic_groups(palette),
    semantic_groups(options),
    markdown_and_help()
  )
end

return M
