# Generated by scripts/generate.py from palette/foundation.json and palette/aliases.json. Do not edit.
nib_light <- c(blue_black = "#285D7C", moss = "#536126", teal = "#17666A", burgundy = "#7C3448", rust = "#8A432C", violet = "#684873", amber = "#77560F", sepia = "#705039", graphite = "#4F5960")
nib_dark <- c(blue_black = "#83A8BB", moss = "#A3AE72", teal = "#6FA8A0", burgundy = "#C17E8B", rust = "#C28168", violet = "#AF97B7", amber = "#C5A667", sepia = "#AE967B", graphite = "#959C98")
